import { getCanvasService } from "../generated/canvas-server/index";
import { getChatService } from "../generated/chat-server/index";

export * from "../generated/canvas-server/index";

export const {
  canvasGetBasicConfig,
  canvasUpdateBasicConfig,
  canvasGetRuntimeBasicConfig,
  canvasListProjects,
  canvasCreateProject,
  canvasDeleteProject,
  canvasGetProject,
  canvasUpdateProject,
  canvasListCanvases,
  canvasCreateCanvas,
  canvasDeleteCanvas,
  canvasGetCanvas,
  canvasUpdateCanvas,
  canvasUpdateCanvasView,
  canvasGetGraph,
  canvasCreateNode,
  canvasUpdateNode,
  canvasDeleteNode,
  canvasBatchDeleteNodes,
  canvasUpdateNodePositions,
  canvasConnectNodes,
  canvasDeleteEdge,
  canvasReorderStoryboard,
  canvasStartGeneration,
  canvasStartNodeGeneration,
  canvasCancelNodeGeneration,
  canvasBatchGetNodeStates,
  canvasListNodeHistories,
  canvasSelectNodeHistory,
  canvasStartNodeAssetMatch,
  canvasCancelNodeAssetMatch,
  canvasSearchNodeAssets,
  canvasCopyNode,
  canvasCreateAsset,
  canvasMaterializeAssetReference,
  canvasMaterializeResourceReference,
  canvasStartStoryboardDrafts,
  canvasCancelStoryboardDrafts,
  canvasConfirmStoryboardDrafts,
  canvasListResources,
  canvasCreateResource,
  canvasCreateResourceFromAsset,
  canvasGetResource,
  canvasUpdateResource,
  canvasDeleteResource,
  canvasListResourceAssets,
  canvasCreateResourceAsset,
  canvasCreateGeneratedResourceAsset,
  canvasUpdateResourceAsset,
  canvasDeleteResourceAsset,
  canvasSetPrimaryResourceAsset,
  canvasReplaceResourceAsset,
  canvasGetResourceGeneration,
  canvasUpdateResourceGeneration,
  canvasStartResourceGeneration,
  canvasGetResourceGenerationRun,
  canvasCancelResourceGeneration,
} = getCanvasService();

export function createCanvasConversation(projectId: string, canvasId: string) {
  return getChatService().createCanvasConversation(
    { project_id: projectId, canvas_id: canvasId },
    { baseURL: "/api/chat-server" },
  );
}
