import { getCanvasService } from "../generated/canvas-server/index";
import { getChatService } from "../generated/chat-server/index";
export type {
  CanvasGenerationState,
  CanvasArchive,
  CanvasResourceVersion,
  CanvasResource,
  CanvasResourceAsset,
  CanvasCreativeAsset,
  CanvasGeneration,
  CanvasGraph,
  CanvasNode,
  CanvasEdge,
  CanvasBoard,
  CanvasProject,
  CanvasMutation,
  CanvasAssetReview,
  CanvasBenefitPackageChoice,
  CanvasProjectAsset,
} from "../generated/canvas-server/index";
export const {
  canvasGenerationStatus,
  canvasStartAllVideoGenerations,
  canvasCreateArchive,
  canvasListArchives,
  canvasCancelArchive,
  canvasArchiveContent,
  canvasReplaceResourceAsset,
  canvasListResourceVersions,
  canvasResourceVersionContent,
  canvasUpdateResourceAsset,
  canvasSetPrimaryResourceAsset,
  canvasDeleteResourceAsset,
  canvasListResources,
  canvasCreateResource,
  canvasUpdateResource,
  canvasDeleteResource,
  canvasListResourceAssets,
  canvasUploadResourceAsset,
  canvasResourceContent,
  canvasCopyResourceToCanvas,
  canvasSearchCreativeAssets,
  canvasUploadNode,
  canvasNodeContent,
  canvasGenerationContent,
  canvasStartGeneration,
  canvasListGenerations,
  canvasCancelGeneration,
  canvasApplyGeneration,
  canvasListProjects,
  canvasGetProject,
  canvasUpdateProject,
  canvasDeleteProject,
  canvasListAssetReviews,
  canvasListAvailableBenefitPackages,
  canvasSubmitAssetReview,
  canvasSubmitProjectAssetReview,
  canvasUploadProjectAsset,
  canvasProjectAssetContent,
  canvasUpdateBoard,
  canvasDeleteBoard,
  canvasUploadBoardCover,
  canvasClearBoardCover,
  canvasBoardCoverContent,
  canvasUpdateCanvasView,
  canvasCreateProject,
  canvasListBoards,
  canvasCreateBoard,
  canvasUploadProjectCover,
  canvasClearProjectCover,
  canvasProjectCoverContent,
  canvasGetGraph,
  canvasMutateGraph,
} = getCanvasService();
export function createCanvasConversation(canvasId: string) {
  return getChatService().createCanvasConversation({ canvas_id: canvasId }, { baseURL: "/api/chat-server" });
}
