import { defineConfig } from "oxlint";

export default defineConfig({
  env: {
    browser: true,
    node: true,
  },
  ignorePatterns: [
    "**/node_modules",
    "**/.git",
    "**/dist",
    "**/build",
    "**/.output",
    "**/.turbo",
    "**/coverage",
    "**/generated",
    "**/__generated__",
    "**/*.generated.*",
    "**/*.gen.*",
    "**/pnpm-lock.yaml",
    "**/.rspack-build",
    "**/dist-mfe",
    "**/migrations/versions",
    "**/patches",
    "apps/backend/libs/transport-ts/src/schema",
  ],
  options: {
    typeAware: true,
  },
  plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "node", "promise", "react", "react-perf", "jsx-a11y"],
  rules: {
    eqeqeq: "warn",
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-constant-binary-expression": "error",
    "no-debugger": "error",
    "no-dupe-else-if": "error",
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "no-fallthrough": "error",
    "no-import-assign": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-promise-executor-return": "error",
    "no-self-assign": "error",
    "no-template-curly-in-string": "error",
    "no-unreachable-loop": "warn",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-private-class-members": "error",
    "no-var": "error",
    "object-shorthand": "error",
    "prefer-const": "error",
    "prefer-object-has-own": "error",
    "typescript/await-thenable": "warn",
    "typescript/consistent-type-exports": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/no-floating-promises": "warn",
    "typescript/no-misused-promises": "warn",
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/no-explicit-any": "warn",
    "typescript/no-non-null-assertion": "off",
    "react/exhaustive-deps": "warn",
    "react/jsx-key": "error",
    "react/no-direct-mutation-state": "error",
    "react/react-compiler": "warn",
    "react/rules-of-hooks": "warn",
    "react/self-closing-comp": "error",
    "jsx-a11y/alt-text": "error",
    "jsx-a11y/aria-props": "error",
    "jsx-a11y/aria-role": "error",
    "jsx-a11y/click-events-have-key-events": "warn",
    "jsx-a11y/no-static-element-interactions": "warn",
  },
  overrides: [
    {
      files: ["apps/backend/**/*.ts", "apps/backend/**/*.mts"],
      env: {
        browser: false,
        node: true,
      },
    },
    {
      files: ["apps/frontend/packages/components/src/shadcn/**"],
      rules: {
        "jsx-a11y/click-events-have-key-events": "off",
        "jsx-a11y/no-static-element-interactions": "off",
      },
    },
  ],
});
