import { ImageIcon, Loader2Icon } from "lucide-react";
import { useChatStore } from "../store/useChatStore";
import { ChatMediaCard } from "./ChatMediaCard";

export type GeneratedImageRef = {
  documentId: string;
  filename: string;
  mediaType: string;
};

export type GenerateImageOutput = {
  ok: boolean;
  status: string;
  images: GeneratedImageRef[];
  error?: string;
  count?: number;
  failed?: number;
};

// generate_image is an inline async-generator tool: it yields a preliminary
// `{ status: "generating" }` so this card can mount immediately, then a final
// `{ status: "completed", images: [...] }` (or `{ ok: false, error }`). The AI
// SDK persists the last yield, so a reloaded conversation renders straight from
// the terminal output.
export function parseGenerateImageOutput(
  output: unknown,
): GenerateImageOutput | null {
  if (!output || typeof output !== "object") return null;
  const raw = output as Record<string, unknown>;
  const images = Array.isArray(raw.images)
    ? raw.images.flatMap((item) => {
        if (!item || typeof item !== "object") return [];
        const row = item as Record<string, unknown>;
        if (typeof row.document_id !== "string") return [];
        return [
          {
            documentId: row.document_id,
            filename: typeof row.filename === "string" ? row.filename : "image",
            mediaType:
              typeof row.media_type === "string" ? row.media_type : "image/png",
          },
        ];
      })
    : [];
  return {
    ok: raw.ok !== false,
    status:
      typeof raw.status === "string"
        ? raw.status
        : images.length > 0
          ? "completed"
          : "generating",
    images,
    error: typeof raw.error === "string" ? raw.error : undefined,
    count: typeof raw.count === "number" ? raw.count : undefined,
    failed: typeof raw.failed === "number" ? raw.failed : undefined,
  };
}

// The transcript never inlines the generated bytes (ADR-0021): completed images
// render as one lightweight card; clicking it opens the shared lightbox, which
// fetches the whole group on demand via useDocumentBlobUrls.
export function ChatImageCard({
  conversationId,
  output,
  state,
}: {
  conversationId: string;
  output: unknown;
  state: string;
}) {
  const openImagePreview = useChatStore((s) => s.openImagePreview);
  const parsed = parseGenerateImageOutput(output);
  const failed = state === "output-error" || parsed?.ok === false;

  if (failed) {
    return (
      <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs leading-relaxed text-red-700">
        {parsed?.error?.trim() || "图片生成失败。"}
      </div>
    );
  }

  const images = parsed?.images ?? [];
  if (parsed?.status === "completed" && images.length > 0) {
    const refs = images.map((image) => ({
      documentId: image.documentId,
      filename: image.filename,
    }));
    const skipped = parsed.failed ?? 0;
    return (
      <ChatMediaCard
        icon={ImageIcon}
        title={images.length > 1 ? "图片组" : "图片"}
        description={`共 ${images.length} 张`}
        note={skipped > 0 ? `${skipped} 张生成失败` : undefined}
        onOpen={() => openImagePreview(conversationId, refs, 0)}
      />
    );
  }

  const generatingCount = parsed?.count ?? 0;
  return (
    <div className="flex items-center gap-2 rounded-lg border bg-muted/20 px-3 py-3 text-sm text-muted-foreground">
      <Loader2Icon className="size-4 shrink-0 animate-spin" />
      <span className="truncate">
        {generatingCount > 1
          ? `正在生成 ${generatingCount} 张图片…`
          : "正在生成图片…"}
      </span>
    </div>
  );
}
