apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
data:
  PORT: "8008"
  ENVIRONMENT: "development"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "telemetry"
  SAMPLE_RATE_PERFORM: "1.0"
  SAMPLE_RATE_EVENT: "1.0"
