apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
data:
  PORT: "8008"
  ENVIRONMENT: "development"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "telemetry"
  SAMPLE_RATE_PERFORM: "1.0"
  SAMPLE_RATE_EVENT: "1.0"
