export const RESOURCE_ASSETS_MODAL_Z_INDEX = 1000;
export const RESOURCE_ASSETS_POPUP_Z_INDEX = 1002;
export const RESOURCE_ASSET_DETAIL_MODAL_Z_INDEX = 1010;
export const RESOURCE_ASSET_DETAIL_POPUP_Z_INDEX = 1012;
export const RESOURCE_GENERATION_EDITOR_MODAL_Z_INDEX = 1020;
export const RESOURCE_GENERATION_EDITOR_POPUP_Z_INDEX = 1022;
