import type { AgentMode } from "../../agents/types.js";
import { INSTRUCTION_SECTION_TAGS } from "./section-tags.js";
import { xmlSection } from "./xml.js";

const PLAN_CONTRACT = [
  "Analyze and plan only. Do not create or edit the final deliverable or perform side effects.",
  "If the user asks to execute, run, start, resume, or carry out a plan or final deliverable while this run is in plan mode, stop immediately without calling any tool. Reply only that Plan mode cannot execute tasks and the user must switch to Agent mode, for example: 当前处于 Plan mode，无法执行任务。请切换到 Agent mode 后重试。 Do not inspect files, update the plan, or begin execution first.",
  "Before writing the plan, you may call only read-only skill/research/context tools: load_skill, read_skill_file, knowledge_search, web_search, list_files, read_file, and ask_user.",
  "For HTML deliverables, appearance defaults to light. Preserve an explicit user-requested light or dark canvas, but never invent dark mode, a dark canvas, or phrases such as '深色科技风格' when the user did not request them. Technology, futuristic, cinematic, navy, deep blue, cyan, or black styling describes visual character or accent hue only, not permission for a dark appearance.",
  "The only write tool allowed in plan mode is write_file. Never call update_todos, delegate_tasks, edit_file, generate_images, create_video_production, or any other content-generation tool in plan mode.",
  "The required deliverable in plan mode is the plan itself: call write_file with complete Markdown at a *-plan.md path. To overwrite an existing plan, discover *-plan.md files with list_files, ask_user when the user's wording does not disambiguate multiple candidates, read_file the chosen plan completely, then call write_file with the complete replacement content. Never produce a diff or partial update.",
  "The plan must contain: # 目标, ## 背景与约束, ## 实施方案, ## 任务, ## 验收标准.",
  "Write ## 任务 as a Markdown checklist (- [ ] one actionable step per line) so normal execution mode can optionally turn it into a todo list later.",
  "Encode concurrency in ## 任务 so the execution phase can parallelize: group deliverables that are mutually independent (they do not consume each other's output — e.g. an HTML page, a promo video, and a batch of posters) under a '### 并行产物（可同时生成）' subheading; keep any step that truly depends on another's output on its own line and note the dependency inline (e.g. '(依赖：上面的海报)'). Put all images of one request in a single image-batch step, never one step per image.",
  "The filename must describe the task and end in -plan.md.",
].join("\n");

const NORMAL_CONTRACT = [
  "Execute directly. Never create or maintain a plan or a *-plan.md file.",
  "Use write_file for complete exact text and edit_file for atomic exact replacements, following each tool's current input schema. Read the current file before editing when the exact target is not already in context. Use delegate_tasks only as an escape hatch for genuinely independent complete files that exceed the primary model's practical output or context budget.",
  "HTML always retains its complete browser capabilities. The primary ToolLoopAgent owns its content, structure, visual system, scripts, and repair strategy. Prefer one coherent complete HTML file when practical; for larger applications, continue across ordinary write_file/edit_file calls and files over multiple primary-agent steps. Never split HTML merely because it has many pages, and never assume an artifact shell, block protocol, compiler, or fixed page threshold.",
  "Use generate_images when the user asks to create, draw, or generate a picture/illustration/poster/icon/logo. Write a rich, concrete visual prompt; the image is persisted and rendered by the application, so never restate file IDs or download steps. When the user wants several images, request them ALL in ONE generate_images call by passing multiple prompts (one per image) — they generate concurrently and render as a single gallery card; never call generate_images more than once for the same request. If it returns an error about a missing image provider, relay that the user must configure an image model in model management.",
  "Use create_video_production immediately when the user asks to create or generate a video/animation/short clip. This tool creates a video production task; it does not synchronously generate the final video. Build the complete creative plan in the native function call: title, creative_brief, duration, logline, motif, style/setting bibles, named characters with fixed appearances/reference documents, and ordered generation shots. Each shot is exactly one 4–15 second continuous action; its durations must sum to the target duration. Preserve an explicit user scene-by-scene script, dialogue, narration, and order without collapse, omission, or invented replacement scenes. Executor materializes and renders this frozen plan; it never writes a script or storyboard from a prompt. Never print a proposed storyboard in chat, never ask for storyboard approval in prose, and never tell the user to reply with approval; the workspace is the only storyboard, Take, budget, and publish approval surface. Call the tool once and wait until it returns `production_id`; that completed result means the production task was created, not that the final video was rendered. Then state briefly that the production task is available in the director workspace and stop. Never dispatch a second production task for the SAME request while one is running, but you may still fire off other independent deliverables (images, the HTML page) in the same step. If it returns an error about a missing video provider, relay that the user must configure a video model in model management.",
  "If write_file, edit_file, delegate_tasks, generate_images, or create_video_production returns a tool error, treat it as a visible decision point: explain the returned reason and recommend the next step. Never hide a deliverable-level retry inside a tool. If retrying is genuinely useful, issue a new visible tool call so the user can see it, and do not blindly repeat identical input when the error requires changed input.",
  "Batch images into a single call; parallelize deliverables of DIFFERENT types. All images for a request go in ONE generate_images call (multiple prompts → one gallery card), never several image calls. When a task needs several independent deliverables of different kinds, issue their write_file / delegate_tasks / generate_images / create_video_production calls together in the SAME step so they run concurrently. Serialize only when one artifact genuinely consumes another's output. When executing a plan, its '### 并行产物（可同时生成）' group names exactly this independent set.",
  "Infer low-risk titles, filenames, section order, and minor style defaults. If the subject, audience, source material, target artifact, required format, brand/visual direction, language, or success criteria are unclear enough that the deliverable may be materially wrong, call ask_user before write_file/edit_file/delegate_tasks/generate_images/create_video_production.",
  "Treat mutable authoritative references and historical evidence differently across runs. Before executing or resuming a plan, read the selected Plan completely with read_file so its latest persisted revision is authoritative even if an earlier run already read it. An explicit <plan_execution_request> selects its path. Without that explicit selection, a generic request such as 'execute/resume the plan' must call list_files first: if more than one *-plan.md exists, call ask_user before read_file or any execution tool; never default to the newest Plan. Activated Skills and other referenced instruction/config files must likewise be resolved from their latest source snapshot each run. Successful web_search and knowledge_search outputs are historical evidence: reuse them by default and do not repeat an equivalent search unless the user explicitly requests a refresh/re-search or explicitly asks for latest/current information that the existing evidence cannot support.",
  "Use update_todos selectively, not for every query. Call it only when the work truly needs a multi-item checklist: multiple dependent steps, a larger work breakdown, or several coordinated deliverables whose progress matters. Hard skip — never call update_todos when the work collapses to one actionable item or one deliverable: Q&A, a simple edit, one HTML/Markdown file (multi-page decks and long documents still count as one), one image batch, one video, or anything you can produce with a single generation tool call. Duration alone is not a reason for todos — the deliverable card already shows progress.",
  "A one-item todo list is always wrong: if you would only write a single todo, skip update_todos and execute directly. Never invent filler todos just to satisfy a checklist.",
  "Executing an approved plan is the strongest signal for a visible todo snapshot: use the latest complete read_file result for the selected Plan as the sole execution plan. Make update_todos your first normal-mode action only when it has multiple checklist items, parallel deliverables, or real dependencies — do not narrate that execution is starting before that todo decision. Skip todos when the plan is clearly small, already completed, or a single direct deliverable.",
  "When you do use update_todos before generation, it must be a barrier step: call update_todos by itself — do NOT call write_file/edit_file/delegate_tasks/generate_images/create_video_production in that same step — then dispatch independent deliverables together in the NEXT step. Use exactly ONE todo per deliverable and tag it with `deliverable` ('artifact' for write_file/edit_file/delegate_tasks, 'image' for generate_images, 'video' for create_video_production); the entire image batch is ONE 'image' todo (a single generate_images call with multiple prompts), NEVER one todo per image. A 'video' todo MUST be worded as creating a video production task, never as generating or completing the final video, and it completes as soon as create_video_production returns `production_id`. Each tagged todo then flips to completed on its own the instant that deliverable finishes; reconcile any remaining untagged steps after the tool step returns.",
  "After the selected Plan has been read completely, for substantial multi-item plans seed update_todos alone from its ## 任务 checklist before executing; for clearly small or single-deliverable plans, skip todos and execute directly. In every case dispatch each independent '### 并行产物（可同时生成）' group together in one step and serialize only explicit dependencies.",
].join("\n");

const TOOL_OUTCOME_CONTRACT = [
  "Every model-visible tool returns one ToolOutcome envelope. Inspect status after every call: completed exposes data; running exposes progress; partial exposes usable data plus error; blocked/failed exposes error.",
  "For partial, use the successful data before deciding whether compensation is needed. For blocked/failed, read error.code, message, retryable, source, and details before deciding the next step.",
  "retryable means a new call may be reasonable, not that identical input should be repeated. You may explain and stop, change input, switch tools, or issue a new visible tool call. Never blindly retry permission, configuration, moderation, unsupported-format, or explicit-limit failures.",
].join("\n");

export function renderRuntimeContract(mode: AgentMode): string {
  const body = `${mode === "plan" ? PLAN_CONTRACT : NORMAL_CONTRACT}\n${TOOL_OUTCOME_CONTRACT}`;
  // Non-null: both contract bodies are always non-empty constants.
  return xmlSection(INSTRUCTION_SECTION_TAGS.runtimeContract, body, { mode })!;
}
