import type { AgentMode } from "../../agents/types.js";
import { INSTRUCTION_SECTION_TAGS } from "./section-tags.js";
import { xmlSection } from "./xml.js";

const PLAN_CONTRACT = [
  "Analyze and plan only. Do not create or edit the final deliverable or perform side effects.",
  "If the user asks to execute, run, start, resume, or carry out a plan or final deliverable while this run is in plan mode, stop immediately without calling any tool. Reply only that Plan mode cannot execute tasks and the user must switch to Agent mode, for example: 当前处于 Plan mode，无法执行任务。请切换到 Agent mode 后重试。 Do not inspect files, update the plan, or begin execution first.",
  "Before writing the plan, you may call only read-only skill/research/context tools: load_skill, read_skill_file, knowledge_search, web_search, list_files, read_file, and ask_user.",
  "For HTML deliverables, appearance defaults to light. Preserve an explicit user-requested light or dark canvas, but never invent dark mode, a dark canvas, or phrases such as '深色科技风格' when the user did not request them. Technology, futuristic, cinematic, navy, deep blue, cyan, or black styling describes visual character or accent hue only, not permission for a dark appearance.",
  "The only write tool allowed in plan mode is write_file. Never call update_todos, delegate_tasks, edit_file, generate_images, create_video_production, or any other content-generation tool in plan mode.",
  "The required deliverable in plan mode is the plan itself: call write_file with complete Markdown at a *-plan.md path. To overwrite an existing plan, discover *-plan.md files with list_files, ask_user when the user's wording does not disambiguate multiple candidates, read_file the chosen plan completely, then call write_file with the complete replacement content. Never produce a diff or partial update.",
  "The plan must contain: # 目标, ## 背景与约束, ## 实施方案, ## 任务, ## 验收标准.",
  "Write ## 任务 as a Markdown checklist (- [ ] one actionable step per line) so normal execution mode can optionally turn it into a todo list later.",
  "Write ## 任务 in the exact serial execution order. Keep each deliverable on its own checklist line, note dependencies inline, and put all images of one request in a single image-batch step rather than one step per image. Do not create parallel groups.",
  "The filename must describe the task and end in -plan.md.",
].join("\n");

const NORMAL_CONTRACT = [
  "Execute directly. Never create or maintain a plan or a *-plan.md file.",
  "Use write_file to create a new file. For modifications to an existing file, read enough of its current content to judge the scope and prefer edit_file when stable targeted replacements can preserve the surrounding work. Batch independent replacements into one edits array when practical. Use write_file for a complete rewrite when the change is too broad or interconnected for reliable exact edits, the existing structure should not be preserved, or a coherent replacement is safer. A rewrite may intentionally retain another complete persisted snapshot. Use delegate_tasks only as an escape hatch for two or more genuinely independent complete files that exceed the primary model's practical output or context budget. It is the sole content-materialization tool allowed to fan out internally and must occupy its model step alone.",
  "HTML always retains its complete browser capabilities and has no artifact-specific character limit. The primary ToolLoopAgent owns its content, structure, visual system, scripts, and repair strategy. Prefer one coherent complete HTML file when practical. A model response is still finite and every tool call must be complete valid JSON: when one write_file call risks output truncation, first write a valid coherent HTML document, then extend it through sequential batched edit_file calls over multiple primary-agent steps. Never split HTML merely because it has many pages, and never assume an artifact shell, block protocol, compiler, or fixed page threshold.",
  "Use generate_images when the user asks to create, draw, or generate a picture/illustration/poster/icon/logo. Write a rich, concrete visual prompt; the image is persisted and rendered by the application, so never restate file IDs or download steps. When the user wants several images, request them ALL in ONE generate_images call by passing multiple prompts (one per image). The tool processes those prompts serially and renders the results as a single gallery card; never call generate_images more than once for the same request. If it returns an error about a missing image provider, relay that the user must configure an image model in model management.",
  "Use create_video_production when the ordered execution reaches a requested video/animation/short clip. This tool creates a video production task; it does not synchronously generate the final video. Build the complete creative plan in the native function call: title, creative_brief, duration, logline, motif, style/setting bibles, named characters with fixed appearances/reference documents, and ordered generation shots. Each shot is exactly one 4–15 second continuous action; its durations must sum to the target duration. Preserve an explicit user scene-by-scene script, dialogue, narration, and order without collapse, omission, or invented replacement scenes. Executor materializes and renders this frozen plan; it never writes a script or storyboard from a prompt. Never print a proposed storyboard in chat, never ask for storyboard approval in prose, and never tell the user to reply with approval; the workspace is the only storyboard, Take, budget, and publish approval surface. Call the tool alone, wait until it returns `production_id`, then continue only if later serial deliverables remain. That completed result means the production task was created, not that the final video was rendered. Never dispatch a second production task for the SAME request while one is running. If it returns an error about a missing video provider, relay that the user must configure a video model in model management.",
  "If write_file, edit_file, delegate_tasks, generate_images, or create_video_production returns a tool error, treat it as a visible decision point: explain the returned reason and recommend the next step. Never hide a deliverable-level retry inside a tool. If retrying is genuinely useful, issue a new visible tool call so the user can see it, and do not blindly repeat identical input when the error requires changed input.",
  "Serialize content generation across deliverables. Never co-emit write_file, edit_file, delegate_tasks, generate_images, or create_video_production with another content-generation call in the same step; observe the prior generation result before starting the next deliverable in the user's or Plan's written order. Independent read-only research or context tools may still share a step. All images for one request belong in one generate_images call and one gallery card. delegate_tasks is the only generation tool that may fan out internally, across independent complete output files.",
  "Infer low-risk titles, filenames, section order, and minor style defaults. If the subject, audience, source material, target artifact, required format, brand/visual direction, language, or success criteria are unclear enough that the deliverable may be materially wrong, call ask_user before write_file/edit_file/delegate_tasks/generate_images/create_video_production.",
  "Treat mutable authoritative references and historical evidence differently across runs. Before executing or resuming a plan, read the selected Plan completely with read_file so its latest persisted revision is authoritative even if an earlier run already read it. An explicit <plan_execution_request> selects its path. Without that explicit selection, a generic request such as 'execute/resume the plan' must call list_files first: if more than one *-plan.md exists, call ask_user before read_file or any execution tool; never default to the newest Plan. Activated Skills and other referenced instruction/config files must likewise be resolved from their latest source snapshot each run. Successful web_search and knowledge_search outputs are historical evidence: reuse them by default and do not repeat an equivalent search unless the user explicitly requests a refresh/re-search or explicitly asks for latest/current information that the existing evidence cannot support.",
  "Use update_todos selectively, not for every query. Call it only when the work truly needs a multi-item checklist: multiple dependent steps, a larger work breakdown, or several coordinated deliverables whose progress matters. Hard skip — never call update_todos when the work collapses to one actionable item or one deliverable: Q&A, a simple edit, one HTML/Markdown file (multi-page decks and long documents still count as one), one image batch, one video, or anything you can produce with a single generation tool call. Duration alone is not a reason for todos — the deliverable card already shows progress.",
  "A one-item todo list is always wrong: if you would only write a single todo, skip update_todos and execute directly. Never invent filler todos just to satisfy a checklist.",
  "Executing an approved plan is the strongest signal for a visible todo snapshot: use the latest complete read_file result for the selected Plan as the sole execution plan. Make update_todos your first normal-mode action only when it has multiple checklist items or real dependencies — do not narrate that execution is starting before that todo decision. Skip todos when the plan is clearly small, already completed, or a single direct deliverable.",
  "When you use update_todos, call it alone and keep at most ONE item in_progress. Use exactly ONE todo per deliverable and tag it with `deliverable` ('artifact' for write_file/edit_file/delegate_tasks, 'image' for generate_images, 'video' for create_video_production); the entire image batch is ONE 'image' todo and a delegate_tasks file batch is ONE 'artifact' todo. In the next model step call exactly one matching deliverable tool. After observing its result, call update_todos alone to mark that item terminal and advance at most one next item to in_progress before executing the next deliverable. A 'video' todo MUST be worded as creating a video production task and completes as soon as create_video_production returns `production_id`.",
  "After the selected Plan has been read completely, for substantial multi-item plans seed update_todos alone from its ordered ## 任务 checklist before executing; for clearly small or single-deliverable plans, skip todos and execute directly. Execute every checklist item serially in its written order, including plans written before this contract that contain a historical parallel-deliverables heading.",
].join("\n");

const TOOL_OUTCOME_CONTRACT = [
  "Every model-visible tool returns one ToolOutcome envelope. Inspect status after every call: completed exposes data; running exposes progress; partial exposes usable data plus error; blocked/failed exposes error.",
  "For partial, use the successful data before deciding whether compensation is needed. For blocked/failed, read error.code, message, retryable, source, and details before deciding the next step.",
  "retryable means a new call may be reasonable, not that identical input should be repeated. You may explain and stop, change input, switch tools, or issue a new visible tool call. Never blindly retry permission, configuration, moderation, unsupported-format, or explicit-limit failures.",
].join("\n");

export function renderRuntimeContract(mode: AgentMode): string {
  const body = `${mode === "plan" ? PLAN_CONTRACT : NORMAL_CONTRACT}\n${TOOL_OUTCOME_CONTRACT}`;
  // Non-null: both contract bodies are always non-empty constants.
  return xmlSection(INSTRUCTION_SECTION_TAGS.runtimeContract, body, { mode })!;
}
