/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assets/{assetID}/revisions/{revisionID}/content": {
        parameters: {
            query?: never;
            header: {
                "X-Auth-Tenant-ID": string;
                "X-Auth-Workspace-ID": string;
                "X-Auth-User-ID": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        get: operations["assetReadContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: operations["assetHeadContent"];
        patch?: never;
        trace?: never;
    };
    "/internal/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Idempotently stream service-produced bytes into an immutable Asset revision */
        post: operations["assetUploadInternal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/assets/{assetID}/revisions/{revisionID}": {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
            };
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        get: operations["assetDescribeRevisionInternal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/assets/{assetID}/revisions/{revisionID}/content": {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
            };
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        get: operations["assetReadContentInternal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: operations["assetHeadContentInternal"];
        patch?: never;
        trace?: never;
    };
    "/internal/claims:activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assetActivateClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/claims:prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assetPrepareClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/claims:release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assetReleaseClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/delivery-capabilities:mint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assetMintDeliveryCapabilities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/upload-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or recover a domain-authorized browser upload session */
        post: operations["assetCreateUploadSessionInternal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/upload-sessions/{uploadID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve an upload session in the creating service scope */
        get: operations["assetDescribeUploadSessionInternal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{assetID}/revisions/{revisionID}/content": {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
                expires: string;
                signature: string;
            };
            header?: never;
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        get: operations["assetReadCapabilityContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: operations["assetHeadCapabilityContent"];
        patch?: never;
        trace?: never;
    };
    "/upload-sessions/{uploadID}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload bytes through a domain-authorized capability */
        put: operations["assetUploadSessionContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Claim: {
            /** Format: uuid */
            asset_id: string;
            /** Format: uuid */
            claim_id: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: int64 */
            generation: number;
            /** @enum {string} */
            kind: "strong" | "snapshot" | "lease" | "weak";
            /** Format: uuid */
            revision_id?: string;
            /** @enum {string} */
            status: "pending" | "active" | "released";
        };
        CreateUploadSessionRequest: {
            category: string;
            filename: string;
            intent_id: string;
            media_type: string;
            /** Format: int64 */
            size_bytes: number;
            tenant_id: string;
            user_id: string;
            workspace_id: string;
        };
        DeliveryCapabilityResponse: {
            items: {
                /** Format: uuid */
                asset_id: string;
                /** Format: date-time */
                expires_at: string;
                /** Format: uuid */
                revision_id: string;
                url: string;
            }[];
        };
        MutateClaimRequest: {
            /** Format: int64 */
            generation: number;
            owner_id: string;
            owner_type: string;
            slot: string;
            tenant_id: string;
            workspace_id: string;
        };
        PrepareClaimRequest: {
            /** Format: uuid */
            asset_id: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: int64 */
            generation: number;
            /** @enum {string} */
            kind: "strong" | "snapshot" | "lease" | "weak";
            owner_id: string;
            owner_type: string;
            /** Format: uuid */
            revision_id?: string;
            slot: string;
            tenant_id: string;
            workspace_id: string;
        };
        Problem: {
            detail?: string;
            status: number;
            title: string;
            type?: string;
        };
        RevisionMetadata: {
            /** Format: uuid */
            asset_id: string;
            category: string;
            created_by: string;
            filename: string;
            media_type: string;
            /** Format: uuid */
            revision_id: string;
            sha256: string;
            /** Format: int64 */
            size_bytes: number;
        };
        UploadResult: {
            /** Format: uuid */
            asset_id: string;
            filename: string;
            media_type: string;
            /** Format: uuid */
            revision_id: string;
            sha256: string;
            /** Format: int64 */
            size_bytes: number;
            url: string;
        };
        UploadSession: {
            /** Format: uuid */
            asset_id?: string;
            category: string;
            /** Format: date-time */
            expires_at: string;
            filename: string;
            intent_id: string;
            media_type: string;
            /** Format: uuid */
            revision_id?: string;
            /** Format: int64 */
            size_bytes: number;
            /** @enum {string} */
            state: "pending" | "uploading" | "completed" | "failed" | "aborted";
            /** Format: uuid */
            upload_session_id: string;
            upload_url: string;
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assetReadContent: {
        parameters: {
            query?: never;
            header: {
                "X-Auth-Tenant-ID": string;
                "X-Auth-Workspace-ID": string;
                "X-Auth-User-ID": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable content */
            200: {
                headers: {
                    "Accept-Ranges"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetHeadContent: {
        parameters: {
            query?: never;
            header: {
                "X-Auth-Tenant-ID": string;
                "X-Auth-Workspace-ID": string;
                "X-Auth-User-ID": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable content */
            200: {
                headers: {
                    "Accept-Ranges"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetUploadInternal: {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
                user_id: string;
                filename: string;
                category: string;
                idempotency_key: string;
            };
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetDescribeRevisionInternal: {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
            };
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionMetadata"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetReadContentInternal: {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
            };
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable content */
            200: {
                headers: {
                    "Accept-Ranges"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetHeadContentInternal: {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
            };
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable content */
            200: {
                headers: {
                    "Accept-Ranges"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetActivateClaim: {
        parameters: {
            query?: never;
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutateClaimRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetPrepareClaim: {
        parameters: {
            query?: never;
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrepareClaimRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetReleaseClaim: {
        parameters: {
            query?: never;
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutateClaimRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetMintDeliveryCapabilities: {
        parameters: {
            query?: never;
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: {
                        /** Format: uuid */
                        asset_id: string;
                        /** Format: uuid */
                        revision_id: string;
                        tenant_id: string;
                        workspace_id: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCapabilityResponse"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetCreateUploadSessionInternal: {
        parameters: {
            query?: never;
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadSessionRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetDescribeUploadSessionInternal: {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
            };
            header: {
                "X-Caller-Service": string;
                "X-Internal-Token": string;
            };
            path: {
                uploadID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetReadCapabilityContent: {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
                expires: string;
                signature: string;
            };
            header?: never;
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable content */
            200: {
                headers: {
                    "Accept-Ranges"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetHeadCapabilityContent: {
        parameters: {
            query: {
                tenant_id: string;
                workspace_id: string;
                expires: string;
                signature: string;
            };
            header?: never;
            path: {
                assetID: string;
                revisionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable content */
            200: {
                headers: {
                    "Accept-Ranges"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    assetUploadSessionContent: {
        parameters: {
            query: {
                expires: string;
                signature: string;
            };
            header?: never;
            path: {
                uploadID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Problem */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
