/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a durable task. Non-blocking: returns immediately with status=queued/running. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description registered TaskType name, e.g. html-artifact */
                        type: string;
                        /** @description calling service, e.g. chat */
                        owner_service: string;
                        /** @description idempotency key scoped to owner_service, e.g. a tool call id */
                        owner_ref: string;
                        /** @description TaskType-specific input, validated against that type's schema */
                        payload: unknown;
                    };
                };
            };
            responses: {
                /** @description task created (or existing task if owner_ref already used) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            type: string;
                            /** @enum {string} */
                            status: "queued" | "running" | "completed" | "failed" | "cancelled";
                            ownerService: string;
                            ownerRef: string;
                            result: unknown;
                            progress: {
                                done: number;
                                total: number;
                            } | null;
                            error: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            finishedAt: string | null;
                        };
                    };
                };
                /** @description unknown task type or invalid payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description task snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            type: string;
                            /** @enum {string} */
                            status: "queued" | "running" | "completed" | "failed" | "cancelled";
                            ownerService: string;
                            ownerRef: string;
                            result: unknown;
                            progress: {
                                done: number;
                                total: number;
                            } | null;
                            error: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            finishedAt: string | null;
                        };
                    };
                };
                /** @description task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description task snapshot after cancellation request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            type: string;
                            /** @enum {string} */
                            status: "queued" | "running" | "completed" | "failed" | "cancelled";
                            ownerService: string;
                            ownerRef: string;
                            result: unknown;
                            progress: {
                                done: number;
                                total: number;
                            } | null;
                            error: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            finishedAt: string | null;
                        };
                    };
                };
                /** @description task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Task: {
            id: string;
            type: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            ownerService: string;
            ownerRef: string;
            result: unknown;
            progress: {
                done: number;
                total: number;
            } | null;
            error: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
        };
        CreateTaskInput: {
            /** @description registered TaskType name, e.g. html-artifact */
            type: string;
            /** @description calling service, e.g. chat */
            owner_service: string;
            /** @description idempotency key scoped to owner_service, e.g. a tool call id */
            owner_ref: string;
            /** @description TaskType-specific input, validated against that type's schema */
            payload: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
