/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Stream
         * @description Upload files, store raw bytes, convert to markdown, stream progress via SSE.
         */
        post: operations["ingest_stream_ingest_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Documents */
        get: operations["list_my_documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Document */
        get: operations["get_my_document_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete My Document */
        delete: operations["delete_my_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        /** Update My Document */
        patch: operations["update_my_document_documents__document_id__patch"];
        trace?: never;
    };
    "/documents/{document_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Document Source */
        get: operations["get_my_document_source_documents__document_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_internal_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_internal_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_internal_documents__document_id__delete"];
        options?: never;
        head?: never;
        /** Update Artifact */
        patch: operations["update_artifact_internal_documents__document_id__patch"];
        trace?: never;
    };
    "/internal/documents/{document_id}/slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Slice */
        get: operations["get_document_slice_internal_documents__document_id__slice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/documents/{document_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Source */
        get: operations["get_document_source_internal_documents__document_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Artifact */
        post: operations["create_artifact_internal_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve Generation */
        post: operations["reserve_generation_internal_artifact_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/claimable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claimable Generations */
        get: operations["list_claimable_generations_internal_artifact_generations_claimable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/unfinished": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Unfinished Generations */
        get: operations["list_unfinished_generations_internal_artifact_generations_unfinished_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation */
        get: operations["get_generation_internal_artifact_generations__generation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Generation */
        post: operations["claim_generation_internal_artifact_generations__generation_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/phase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Generation Phase */
        post: operations["update_generation_phase_internal_artifact_generations__generation_id__phase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew Generation */
        post: operations["renew_generation_internal_artifact_generations__generation_id__renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Generation */
        post: operations["cancel_generation_internal_artifact_generations__generation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fail Generation */
        post: operations["fail_generation_internal_artifact_generations__generation_id__fail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Plan */
        put: operations["save_plan_internal_artifact_generations__generation_id__plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Block */
        put: operations["save_block_internal_artifact_generations__generation_id__blocks__block_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ready Blocks */
        get: operations["list_ready_blocks_internal_artifact_generations__generation_id__blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/documents/{document_id}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Workspace */
        get: operations["get_latest_workspace_internal_artifact_generations_documents__document_id__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Revision */
        post: operations["publish_revision_internal_artifact_generations__generation_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactBlockPlan */
        ArtifactBlockPlan: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Brief */
            brief: string;
        };
        /** ArtifactGeneration */
        ArtifactGeneration: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Total Blocks */
            total_blocks: number;
            /** Completed Blocks */
            completed_blocks: number;
            /** Failed Blocks */
            failed_blocks: number;
            /** Error */
            error: string | null;
            /** Attempt */
            attempt: number;
            /** Run Id */
            run_id: string | null;
            /** Tool Call Id */
            tool_call_id: string | null;
            /** Lease Owner */
            lease_owner: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
        };
        /** ArtifactGenerationDetail */
        ArtifactGenerationDetail: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Total Blocks */
            total_blocks: number;
            /** Completed Blocks */
            completed_blocks: number;
            /** Failed Blocks */
            failed_blocks: number;
            /** Error */
            error: string | null;
            /** Attempt */
            attempt: number;
            /** Run Id */
            run_id: string | null;
            /** Tool Call Id */
            tool_call_id: string | null;
            /** Lease Owner */
            lease_owner: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            /** User Id */
            user_id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Brief */
            brief: string;
            /** Manifest */
            manifest?: {
                [key: string]: unknown;
            } | null;
        };
        /** ArtifactLeaseInput */
        ArtifactLeaseInput: {
            /** User Id */
            user_id: string;
            /** Owner */
            owner: string;
            /**
             * Lease Seconds
             * @default 60
             */
            lease_seconds: number;
        };
        /** ArtifactMutationInput */
        ArtifactMutationInput: {
            /** User Id */
            user_id: string;
            /** Owner */
            owner?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ArtifactPhaseInput */
        ArtifactPhaseInput: {
            /** User Id */
            user_id: string;
            /** Owner */
            owner: string;
            /** Phase */
            phase: string;
        };
        /** ArtifactRevisionWorkspace */
        ArtifactRevisionWorkspace: {
            /** Document Id */
            document_id: string;
            /** Revision Id */
            revision_id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Blocks */
            blocks: components["schemas"]["StoredArtifactBlock"][];
        };
        /** Body_ingest_stream_ingest_stream_post */
        Body_ingest_stream_ingest_stream_post: {
            /** Files */
            files: string[];
            /** Client Refs */
            client_refs: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Provider Id */
            provider_id?: string | null;
        };
        /** ClaimableArtifactJob */
        ClaimableArtifactJob: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Total Blocks */
            total_blocks: number;
            /** Completed Blocks */
            completed_blocks: number;
            /** Failed Blocks */
            failed_blocks: number;
            /** Error */
            error: string | null;
            /** Attempt */
            attempt: number;
            /** Run Id */
            run_id: string | null;
            /** Tool Call Id */
            tool_call_id: string | null;
            /** Lease Owner */
            lease_owner: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            /** User Id */
            user_id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Brief */
            brief: string;
        };
        /** CreateArtifactInput */
        CreateArtifactInput: {
            /** User Id */
            user_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Content */
            content: string;
            /** Mime Type */
            mime_type?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "source" | "artifact";
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /**
             * Content Md
             * @default
             */
            content_md: string;
            /**
             * Source Size
             * @default 0
             */
            source_size: number;
            /** Source Mime Type */
            source_mime_type?: string | null;
            /** Object Bucket */
            object_bucket?: string | null;
            /** Object Key */
            object_key?: string | null;
            /** Object Sha256 */
            object_sha256?: string | null;
            /** Source Filename */
            source_filename?: string | null;
            /**
             * Ingest Status
             * @default ready
             * @enum {string}
             */
            ingest_status: "pending" | "storing" | "converting" | "ready" | "failed";
            /**
             * Ingest Progress
             * @default 100
             */
            ingest_progress: number;
            /** Ingest Error */
            ingest_error?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentSlice */
        DocumentSlice: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Content */
            content: string;
            /**
             * Start
             * @default 0
             */
            start: number;
            /** Total Chars */
            total_chars: number;
            /** Next Start */
            next_start?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PublishArtifactRevisionInput */
        PublishArtifactRevisionInput: {
            /** User Id */
            user_id: string;
            /** Compiled Html */
            compiled_html: string;
        };
        /** PublishedArtifactRevision */
        PublishedArtifactRevision: {
            /** Document Id */
            document_id: string;
            /** Revision Id */
            revision_id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /**
             * Mime Type
             * @default text/html
             */
            mime_type: string;
            /** Total Chars */
            total_chars: number;
        };
        /** ReserveArtifactGenerationInput */
        ReserveArtifactGenerationInput: {
            /** User Id */
            user_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /**
             * Mode
             * @default document
             * @enum {string}
             */
            mode: "document" | "presentation" | "dashboard";
            /** Brief */
            brief: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Base Revision Id */
            base_revision_id?: string | null;
            /** Document Id */
            document_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Resume Generation Id */
            resume_generation_id?: string | null;
        };
        /** SaveArtifactBlockInput */
        SaveArtifactBlockInput: {
            /** User Id */
            user_id: string;
            /** Content */
            content: string;
            /**
             * Failed
             * @default false
             */
            failed: boolean;
        };
        /** SaveArtifactPlanInput */
        SaveArtifactPlanInput: {
            /** User Id */
            user_id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Blocks */
            blocks: components["schemas"]["ArtifactBlockPlan"][];
        };
        /** StoredArtifactBlock */
        StoredArtifactBlock: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Position */
            position: number;
            /** Content */
            content: string;
        };
        /** UpdateArtifactInput */
        UpdateArtifactInput: {
            /** User Id */
            user_id: string;
            /** Title */
            title?: string | null;
            /** Filename */
            filename?: string | null;
            /** Content */
            content?: string | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Expected Updated At */
            expected_updated_at?: string | null;
        };
        /** UpdateDocumentInput */
        UpdateDocumentInput: {
            /** Title */
            title?: string | null;
            /** Content Md */
            content_md?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_stream_ingest_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_stream_ingest_stream_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_documents_documents_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_my_document_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDocumentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_document_source_documents__document_id__source_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_internal_documents_get: {
        parameters: {
            query: {
                user_id: string;
                conversation_id?: string | null;
                kind?: string | null;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_internal_documents__document_id__get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_internal_documents__document_id__delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_artifact_internal_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArtifactInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_slice_internal_documents__document_id__slice_get: {
        parameters: {
            query: {
                user_id: string;
                start?: number;
                max_chars?: number;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSlice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_source_internal_documents__document_id__source_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_artifact_internal_artifacts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtifactInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reserve_generation_internal_artifact_generations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveArtifactGenerationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claimable_generations_internal_artifact_generations_claimable_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimableArtifactJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_unfinished_generations_internal_artifact_generations_unfinished_get: {
        parameters: {
            query: {
                user_id: string;
                conversation_id?: string | null;
                run_id?: string | null;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_internal_artifact_generations__generation_id__get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGenerationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_generation_internal_artifact_generations__generation_id__claim_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactLeaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_generation_phase_internal_artifact_generations__generation_id__phase_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactPhaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_generation_internal_artifact_generations__generation_id__renew_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactLeaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_generation_internal_artifact_generations__generation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactMutationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fail_generation_internal_artifact_generations__generation_id__fail_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactMutationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_plan_internal_artifact_generations__generation_id__plan_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveArtifactPlanInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_block_internal_artifact_generations__generation_id__blocks__block_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveArtifactBlockInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ready_blocks_internal_artifact_generations__generation_id__blocks_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredArtifactBlock"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_workspace_internal_artifact_generations_documents__document_id__latest_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRevisionWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_revision_internal_artifact_generations__generation_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishArtifactRevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedArtifactRevision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
