/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Livez */
        get: operations["livez_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Upload files, store raw bytes, and schedule background conversion.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Documents */
        get: operations["list_my_documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Delete My Documents
         * @description Delete several documents in one transaction.
         *
         *     Same policy as single delete: an org_admin may delete any of the org's
         *     documents; a member may delete only their own uploads. If ANY requested id
         *     is outside the org or not deletable by the caller, the whole batch is
         *     rejected with 403 — no silent partial success that would mislead the caller.
         *     Object-store blobs are best-effort purged and RAG `document_chunks` drop via
         *     the FK `ON DELETE CASCADE`.
         */
        post: operations["batch_delete_my_documents_documents_batch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Document */
        get: operations["get_my_document_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete My Document */
        delete: operations["delete_my_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        /** Update My Document */
        patch: operations["update_my_document_documents__document_id__patch"];
        trace?: never;
    };
    "/documents/{document_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex My Document
         * @description Re-queue a document for background RAG indexing (retry a skipped/failed
         *     index, or rebuild after provider changes).
         */
        post: operations["reindex_my_document_documents__document_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Document Source */
        get: operations["get_my_document_source_documents__document_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_internal_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_internal_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_internal_documents__document_id__delete"];
        options?: never;
        head?: never;
        /** Update Artifact */
        patch: operations["update_artifact_internal_documents__document_id__patch"];
        trace?: never;
    };
    "/internal/documents/{document_id}/slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Slice
         * @description Read a bounded slice of the converted markdown. When the document is still
         *     converting in the background, ``wait_ms`` long-polls until it is ``ready`` (or
         *     ``failed``/timeout) so a caller that just uploaded can read as soon as convert
         *     finishes instead of getting an empty body. ``state`` distinguishes the outcome:
         *     ``ready`` (real content), ``processing`` (retry later), ``failed`` (see error).
         */
        get: operations["get_document_slice_internal_documents__document_id__slice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/documents/{document_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Source */
        get: operations["get_document_source_internal_documents__document_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Artifact */
        post: operations["create_artifact_internal_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/media-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Media Document
         * @description Persist agent-generated binary media (e.g. a generated image) as a document.
         *
         *     Mirrors the artifact-publish path: bytes go into the object store and the
         *     document row records ``object_bucket``/``object_key`` so the existing
         *     ``/documents/{id}/source`` route serves them. Idempotent on
         *     ``idempotency_key`` (typically the tool-call id) so a retried generation
         *     reuses the same document instead of duplicating storage.
         */
        post: operations["create_media_document_internal_media_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/staged-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Staged Media */
        post: operations["create_staged_media_internal_staged_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/staged-media/{staged_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Staged Media */
        get: operations["get_staged_media_internal_staged_media__staged_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/staged-media/{staged_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Staged Media Source */
        get: operations["get_staged_media_source_internal_staged_media__staged_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/staged-media/{staged_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Staged Media */
        post: operations["publish_staged_media_internal_staged_media__staged_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/staged-media/{staged_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Staged Media */
        post: operations["discard_staged_media_internal_staged_media__staged_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/resource-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Resource Url */
        post: operations["create_resource_url_documents__document_id__resource_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Signed Resource */
        get: operations["get_signed_resource_resources__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve Generation */
        post: operations["reserve_generation_internal_artifact_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fail Generation */
        post: operations["fail_generation_internal_artifact_generations__generation_id__fail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Generation */
        post: operations["cancel_generation_internal_artifact_generations__generation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Plan */
        put: operations["save_plan_internal_artifact_generations__generation_id__plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Block */
        put: operations["save_block_internal_artifact_generations__generation_id__blocks__block_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ready Blocks */
        get: operations["list_ready_blocks_internal_artifact_generations__generation_id__blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/documents/{document_id}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Workspace */
        get: operations["get_latest_workspace_internal_artifact_generations_documents__document_id__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/artifact-generations/{generation_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Revision */
        post: operations["publish_revision_internal_artifact_generations__generation_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/conversation-artifact-cleanups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cleanup Conversation Artifacts Route */
        post: operations["cleanup_conversation_artifacts_route_internal_conversation_artifact_cleanups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve Chunks */
        post: operations["retrieve_chunks_internal_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactBlockPlan */
        ArtifactBlockPlan: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Source Version Id */
            source_version_id?: string | null;
        };
        /** ArtifactGeneration */
        ArtifactGeneration: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Total Blocks */
            total_blocks: number;
            /** Completed Blocks */
            completed_blocks: number;
            /** Failed Blocks */
            failed_blocks: number;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** ArtifactRevisionWorkspace */
        ArtifactRevisionWorkspace: {
            /** Document Id */
            document_id: string;
            /** Revision Id */
            revision_id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Blocks */
            blocks: components["schemas"]["StoredArtifactBlock"][];
        };
        /** BatchDeleteInput */
        BatchDeleteInput: {
            /** Ids */
            ids: string[];
        };
        /** BatchDeleteResult */
        BatchDeleteResult: {
            /** Requested */
            requested: number;
            /** Deleted */
            deleted: number;
        };
        /** Body_ingest_ingest_post */
        Body_ingest_ingest_post: {
            /** Files */
            files: string[];
            /** Client Refs */
            client_refs: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Provider Id */
            provider_id?: string | null;
        };
        /** CancelArtifactGenerationInput */
        CancelArtifactGenerationInput: {
            /** User Id */
            user_id: string;
        };
        /** CleanupConversationArtifactsInput */
        CleanupConversationArtifactsInput: {
            /** Conversation Id */
            conversation_id: string;
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
        };
        /** CleanupConversationArtifactsResult */
        CleanupConversationArtifactsResult: {
            /** Conversation Id */
            conversation_id: string;
            /** Deleted Documents */
            deleted_documents: number;
            /** Deleted Generations */
            deleted_generations: number;
            /** Deleted Blocks */
            deleted_blocks: number;
            /** Deleted Staged Media */
            deleted_staged_media: number;
            /** Deleted Objects */
            deleted_objects: number;
        };
        /** CreateArtifactInput */
        CreateArtifactInput: {
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Content */
            content: string;
            /** Mime Type */
            mime_type?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /**
         * CreateMediaDocumentInput
         * @description Persist agent-generated binary media (image/video/audio) as a document.
         *
         *     The bytes are copied into the object store and served back via the existing
         *     ``/documents/{id}/source`` route. Callers must never persist a provider's
         *     temporary URL as the durable source of truth (ADR-0014).
         */
        CreateMediaDocumentInput: {
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Data Base64 */
            data_base64: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** CreateStagedMediaInput */
        CreateStagedMediaInput: {
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Data Base64 */
            data_base64: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "source" | "artifact";
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /**
             * Content Md
             * @default
             */
            content_md: string;
            /**
             * Source Size
             * @default 0
             */
            source_size: number;
            /** Source Mime Type */
            source_mime_type?: string | null;
            /** Object Bucket */
            object_bucket?: string | null;
            /** Object Key */
            object_key?: string | null;
            /** Object Sha256 */
            object_sha256?: string | null;
            /** Source Filename */
            source_filename?: string | null;
            /**
             * Ingest Status
             * @default ready
             * @enum {string}
             */
            ingest_status: "pending" | "storing" | "received" | "converting" | "ready" | "failed";
            /**
             * Ingest Progress
             * @default 100
             */
            ingest_progress: number;
            /** Ingest Error */
            ingest_error?: string | null;
            /**
             * Index Status
             * @default skipped
             * @enum {string}
             */
            index_status: "pending" | "indexing" | "indexed" | "skipped" | "failed";
            /** Index Error */
            index_error?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentResourceURL */
        DocumentResourceURL: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Mime Type */
            mime_type: string;
            /** Filename */
            filename: string;
        };
        /** DocumentSlice */
        DocumentSlice: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Content */
            content: string;
            /**
             * Start
             * @default 0
             */
            start: number;
            /** Total Chars */
            total_chars: number;
            /** Next Start */
            next_start?: number | null;
            /**
             * State
             * @default ready
             * @enum {string}
             */
            state: "ready" | "processing" | "failed";
            /** Error */
            error?: string | null;
        };
        /** FailArtifactGenerationInput */
        FailArtifactGenerationInput: {
            /** User Id */
            user_id: string;
            /** Error */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestFailure */
        IngestFailure: {
            /** Index */
            index: number;
            /** Client Ref */
            client_ref: string;
            /** Artifact Id */
            artifact_id?: string | null;
            /** Error */
            error: string;
            /** Code */
            code?: string | null;
        };
        /** IngestReceipt */
        IngestReceipt: {
            /** Index */
            index: number;
            /** Client Ref */
            client_ref: string;
            document: components["schemas"]["Document"];
        };
        /** IngestResult */
        IngestResult: {
            /** Documents */
            documents: components["schemas"]["IngestReceipt"][];
            /** Failed */
            failed?: components["schemas"]["IngestFailure"][];
        };
        /** PublishArtifactRevisionInput */
        PublishArtifactRevisionInput: {
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
            /** Compiled Html */
            compiled_html: string;
            /** Expected Object Sha256 */
            expected_object_sha256?: string | null;
        };
        /** PublishedArtifactRevision */
        PublishedArtifactRevision: {
            /** Document Id */
            document_id: string;
            /** Revision Id */
            revision_id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /**
             * Mime Type
             * @default text/html
             */
            mime_type: string;
            /** Total Chars */
            total_chars: number;
        };
        /** ReserveArtifactGenerationInput */
        ReserveArtifactGenerationInput: {
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /**
             * Mode
             * @default document
             * @enum {string}
             */
            mode: "document" | "presentation" | "dashboard";
            /** Brief */
            brief: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Document Id */
            document_id?: string | null;
            /** Base Revision Id */
            base_revision_id?: string | null;
        };
        /** RetrieveInput */
        RetrieveInput: {
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
            /** Query */
            query: string;
            /** Top K */
            top_k?: number | null;
        };
        /** RetrieveResult */
        RetrieveResult: {
            /** Query */
            query: string;
            /** Chunks */
            chunks: components["schemas"]["RetrievedChunk"][];
            /** Note */
            note?: string | null;
        };
        /** RetrievedChunk */
        RetrievedChunk: {
            /** Document Id */
            document_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
        };
        /** SaveArtifactBlockInput */
        SaveArtifactBlockInput: {
            /** User Id */
            user_id: string;
            /** Content */
            content: string;
            /**
             * Failed
             * @default false
             */
            failed: boolean;
        };
        /** SaveArtifactPlanInput */
        SaveArtifactPlanInput: {
            /** User Id */
            user_id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Blocks */
            blocks: components["schemas"]["ArtifactBlockPlan"][];
        };
        /** StagedMedia */
        StagedMedia: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size */
            size: number;
            /** Object Sha256 */
            object_sha256: string;
            /**
             * Status
             * @enum {string}
             */
            status: "staged" | "published" | "discarded";
            /** Document Id */
            document_id?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** StagedMediaActionInput */
        StagedMediaActionInput: {
            /** User Id */
            user_id: string;
            /** Org Id */
            org_id: string;
        };
        /** StoredArtifactBlock */
        StoredArtifactBlock: {
            /** Id */
            id: string;
            /** Version Id */
            version_id: string;
            /** Type */
            type: string;
            /** Position */
            position: number;
            /** Content Sha256 */
            content_sha256: string;
            /** Content */
            content: string;
        };
        /** UpdateArtifactInput */
        UpdateArtifactInput: {
            /** User Id */
            user_id: string;
            /** Title */
            title?: string | null;
            /** Filename */
            filename?: string | null;
            /** Content */
            content?: string | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Expected Updated At */
            expected_updated_at?: string | null;
        };
        /** UpdateDocumentInput */
        UpdateDocumentInput: {
            /** Title */
            title?: string | null;
            /** Content Md */
            content_md?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    livez_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_documents_documents_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_my_documents_documents_batch_delete_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_my_document_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDocumentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_my_document_documents__document_id__reindex_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_document_source_documents__document_id__source_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_internal_documents_get: {
        parameters: {
            query: {
                user_id: string;
                conversation_id?: string | null;
                kind?: string | null;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_internal_documents__document_id__get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_internal_documents__document_id__delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_artifact_internal_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArtifactInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_slice_internal_documents__document_id__slice_get: {
        parameters: {
            query: {
                user_id: string;
                start?: number;
                max_chars?: number;
                wait_ms?: number;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSlice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_source_internal_documents__document_id__source_get: {
        parameters: {
            query: {
                user_id: string;
                max_dim?: number | null;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_artifact_internal_artifacts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtifactInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_media_document_internal_media_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMediaDocumentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_staged_media_internal_staged_media_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStagedMediaInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedMedia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staged_media_internal_staged_media__staged_id__get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                staged_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedMedia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staged_media_source_internal_staged_media__staged_id__source_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                staged_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_staged_media_internal_staged_media__staged_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                staged_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StagedMediaActionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_staged_media_internal_staged_media__staged_id__discard_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                staged_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StagedMediaActionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedMedia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resource_url_documents__document_id__resource_url_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Auth-Name"?: string | null;
                "X-Auth-Email"?: string | null;
                "X-Auth-User-ID"?: string | null;
                "X-Auth-Org-ID"?: string | null;
                "X-Auth-Org-Role"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResourceURL"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_signed_resource_resources__document_id__get: {
        parameters: {
            query: {
                expires: number;
                version: string;
                signature: string;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reserve_generation_internal_artifact_generations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveArtifactGenerationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fail_generation_internal_artifact_generations__generation_id__fail_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FailArtifactGenerationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_generation_internal_artifact_generations__generation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelArtifactGenerationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_plan_internal_artifact_generations__generation_id__plan_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveArtifactPlanInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_block_internal_artifact_generations__generation_id__blocks__block_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                generation_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveArtifactBlockInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactGeneration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ready_blocks_internal_artifact_generations__generation_id__blocks_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredArtifactBlock"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_workspace_internal_artifact_generations_documents__document_id__latest_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRevisionWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_revision_internal_artifact_generations__generation_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishArtifactRevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedArtifactRevision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_conversation_artifacts_route_internal_conversation_artifact_cleanups_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupConversationArtifactsInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupConversationArtifactsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_chunks_internal_retrieve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Token"?: string | null;
                "X-Caller-Service"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrieveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
