-- Canonical reinstall-only schema baseline. See ADR-0073.
-- The migration runner owns the migration table and version/checksum update.




SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;




SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.events_business (
    id bigint NOT NULL,
    ts_server timestamp(3) without time zone NOT NULL,
    ts_client timestamp(3) without time zone DEFAULT NULL::timestamp without time zone,
    app character varying(32) NOT NULL,
    env character varying(32) NOT NULL,
    release character varying(128) DEFAULT ''::character varying NOT NULL,
    user_id character varying(64) DEFAULT NULL::character varying,
    username character varying(120) DEFAULT NULL::character varying,
    is_admin smallint DEFAULT 0 NOT NULL,
    device_id character varying(128) NOT NULL,
    session_id character varying(128) NOT NULL,
    trace_id character varying(64) DEFAULT NULL::character varying,
    route character varying(256) DEFAULT ''::character varying NOT NULL,
    user_agent character varying(512) DEFAULT ''::character varying NOT NULL,
    name character varying(128) NOT NULL,
    payload jsonb
);



ALTER TABLE public.events_business ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_business_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.events_error (
    id bigint NOT NULL,
    ts_server timestamp(3) without time zone NOT NULL,
    ts_client timestamp(3) without time zone DEFAULT NULL::timestamp without time zone,
    app character varying(32) NOT NULL,
    env character varying(32) NOT NULL,
    release character varying(128) DEFAULT ''::character varying NOT NULL,
    user_id character varying(64) DEFAULT NULL::character varying,
    username character varying(120) DEFAULT NULL::character varying,
    is_admin smallint DEFAULT 0 NOT NULL,
    device_id character varying(128) NOT NULL,
    session_id character varying(128) NOT NULL,
    trace_id character varying(64) DEFAULT NULL::character varying,
    route character varying(256) DEFAULT ''::character varying NOT NULL,
    user_agent character varying(512) DEFAULT ''::character varying NOT NULL,
    fingerprint character varying(32) NOT NULL,
    name character varying(256) NOT NULL,
    message text,
    stack text,
    payload jsonb
);



ALTER TABLE public.events_error ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_error_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.events_perform (
    id bigint NOT NULL,
    ts_server timestamp(3) without time zone NOT NULL,
    ts_client timestamp(3) without time zone DEFAULT NULL::timestamp without time zone,
    app character varying(32) NOT NULL,
    env character varying(32) NOT NULL,
    release character varying(128) DEFAULT ''::character varying NOT NULL,
    user_id character varying(64) DEFAULT NULL::character varying,
    username character varying(120) DEFAULT NULL::character varying,
    is_admin smallint DEFAULT 0 NOT NULL,
    device_id character varying(128) NOT NULL,
    session_id character varying(128) NOT NULL,
    trace_id character varying(64) DEFAULT NULL::character varying,
    route character varying(256) DEFAULT ''::character varying NOT NULL,
    user_agent character varying(512) DEFAULT ''::character varying NOT NULL,
    metric character varying(64) NOT NULL,
    value double precision DEFAULT 0 NOT NULL,
    payload jsonb
);



ALTER TABLE public.events_perform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_perform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.events_warning (
    id bigint NOT NULL,
    ts_server timestamp(3) without time zone NOT NULL,
    ts_client timestamp(3) without time zone DEFAULT NULL::timestamp without time zone,
    app character varying(32) NOT NULL,
    env character varying(32) NOT NULL,
    release character varying(128) DEFAULT ''::character varying NOT NULL,
    user_id character varying(64) DEFAULT NULL::character varying,
    username character varying(120) DEFAULT NULL::character varying,
    is_admin smallint DEFAULT 0 NOT NULL,
    device_id character varying(128) NOT NULL,
    session_id character varying(128) NOT NULL,
    trace_id character varying(64) DEFAULT NULL::character varying,
    route character varying(256) DEFAULT ''::character varying NOT NULL,
    user_agent character varying(512) DEFAULT ''::character varying NOT NULL,
    level character varying(32) DEFAULT 'warning'::character varying NOT NULL,
    message text,
    payload jsonb
);



ALTER TABLE public.events_warning ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_warning_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.sessions (
    app character varying(32) NOT NULL,
    session_id character varying(128) NOT NULL,
    ts_server timestamp(3) without time zone NOT NULL,
    env character varying(32) NOT NULL,
    release character varying(128) DEFAULT ''::character varying NOT NULL,
    user_id character varying(64) DEFAULT NULL::character varying,
    username character varying(120) DEFAULT NULL::character varying,
    is_admin smallint DEFAULT 0 NOT NULL,
    device_id character varying(128) NOT NULL,
    route character varying(256) DEFAULT ''::character varying NOT NULL,
    user_agent character varying(512) DEFAULT ''::character varying NOT NULL,
    event_count integer DEFAULT 0 NOT NULL
);



ALTER TABLE ONLY public.events_business
    ADD CONSTRAINT events_business_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.events_error
    ADD CONSTRAINT events_error_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.events_perform
    ADD CONSTRAINT events_perform_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.events_warning
    ADD CONSTRAINT events_warning_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (app, session_id);



CREATE INDEX ix_events_business_app_name_ts ON public.events_business USING btree (app, name, ts_server);



CREATE INDEX ix_events_business_ts ON public.events_business USING btree (ts_server);



CREATE INDEX ix_events_error_app_fp_ts ON public.events_error USING btree (app, fingerprint, ts_server);



CREATE INDEX ix_events_error_ts ON public.events_error USING btree (ts_server);



CREATE INDEX ix_events_error_user_ts ON public.events_error USING btree (user_id, ts_server);



CREATE INDEX ix_events_perform_app_metric_ts ON public.events_perform USING btree (app, metric, ts_server);



CREATE INDEX ix_events_perform_ts ON public.events_perform USING btree (ts_server);



CREATE INDEX ix_events_perform_user_ts ON public.events_perform USING btree (user_id, ts_server DESC);



CREATE INDEX ix_events_warning_app_level_ts ON public.events_warning USING btree (app, level, ts_server);



CREATE INDEX ix_events_warning_ts ON public.events_warning USING btree (ts_server);



CREATE INDEX ix_sessions_ts ON public.sessions USING btree (ts_server);
