-- Telemetry service PostgreSQL schema (v1.0.0).
--
-- This file is service-owned, mirroring the convention used by iam / admin /
-- gateway. db-init (infra/single-vps/Dockerfile.db-init) and the dev bootstrap
-- (scripts/db-bootstrap.sh → scripts/db-migrate.sh) both apply it.
--
-- All statements use IF NOT EXISTS so re-running is a cheap no-op.
--
-- We dropped ClickHouse for the demo phase. The MergeTree-specific features
-- it provided are emulated with vanilla PostgreSQL: row-level append for the
-- event tables, and `INSERT ... ON CONFLICT DO UPDATE` (UPSERT) on `sessions`
-- for the ReplacingMergeTree-style "latest row wins, event_count accumulates"
-- semantics. TTL is deferred to a future cron job; demo volume doesn't need it.

CREATE TABLE IF NOT EXISTS migration (
  id smallint NOT NULL,
  version varchar(32) NOT NULL,
  update_time timestamptz NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO migration (id, version, update_time)
VALUES (1, 'v0.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

-- ─── events_perform ─────────────────────────────────────────────
-- Frontend web-vitals (LCP/CLS/INP/...) and ad-hoc client metrics.
CREATE TABLE IF NOT EXISTS events_perform (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  ts_server timestamp(3) NOT NULL,
  ts_client timestamp(3) DEFAULT NULL,
  app varchar(32) NOT NULL,
  env varchar(32) NOT NULL,
  release varchar(128) NOT NULL DEFAULT '',
  user_id varchar(64) DEFAULT NULL,
  username varchar(120) DEFAULT NULL,
  is_admin smallint NOT NULL DEFAULT 0,
  device_id varchar(128) NOT NULL,
  session_id varchar(128) NOT NULL,
  trace_id varchar(64) DEFAULT NULL,
  route varchar(256) NOT NULL DEFAULT '',
  user_agent varchar(512) NOT NULL DEFAULT '',
  metric varchar(64) NOT NULL,
  value double precision NOT NULL DEFAULT 0,
  payload jsonb DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_events_perform_app_metric_ts ON events_perform (app, metric, ts_server);
CREATE INDEX IF NOT EXISTS ix_events_perform_ts ON events_perform (ts_server);

-- ─── events_error ───────────────────────────────────────────────
-- Uncaught exceptions, unhandled rejections, network failures, etc.
-- `list_errors` filters by user_id when caller is not admin; index reflects.
CREATE TABLE IF NOT EXISTS events_error (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  ts_server timestamp(3) NOT NULL,
  ts_client timestamp(3) DEFAULT NULL,
  app varchar(32) NOT NULL,
  env varchar(32) NOT NULL,
  release varchar(128) NOT NULL DEFAULT '',
  user_id varchar(64) DEFAULT NULL,
  username varchar(120) DEFAULT NULL,
  is_admin smallint NOT NULL DEFAULT 0,
  device_id varchar(128) NOT NULL,
  session_id varchar(128) NOT NULL,
  trace_id varchar(64) DEFAULT NULL,
  route varchar(256) NOT NULL DEFAULT '',
  user_agent varchar(512) NOT NULL DEFAULT '',
  fingerprint varchar(32) NOT NULL,
  name varchar(256) NOT NULL,
  message text,
  stack text,
  payload jsonb DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_events_error_user_ts ON events_error (user_id, ts_server);
CREATE INDEX IF NOT EXISTS ix_events_error_app_fp_ts ON events_error (app, fingerprint, ts_server);
CREATE INDEX IF NOT EXISTS ix_events_error_ts ON events_error (ts_server);

-- ─── events_warning ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events_warning (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  ts_server timestamp(3) NOT NULL,
  ts_client timestamp(3) DEFAULT NULL,
  app varchar(32) NOT NULL,
  env varchar(32) NOT NULL,
  release varchar(128) NOT NULL DEFAULT '',
  user_id varchar(64) DEFAULT NULL,
  username varchar(120) DEFAULT NULL,
  is_admin smallint NOT NULL DEFAULT 0,
  device_id varchar(128) NOT NULL,
  session_id varchar(128) NOT NULL,
  trace_id varchar(64) DEFAULT NULL,
  route varchar(256) NOT NULL DEFAULT '',
  user_agent varchar(512) NOT NULL DEFAULT '',
  level varchar(32) NOT NULL DEFAULT 'warning',
  message text,
  payload jsonb DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_events_warning_app_level_ts ON events_warning (app, level, ts_server);
CREATE INDEX IF NOT EXISTS ix_events_warning_ts ON events_warning (ts_server);

-- ─── events_business ────────────────────────────────────────────
-- Arbitrary client-side business events (named, with payload).
CREATE TABLE IF NOT EXISTS events_business (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  ts_server timestamp(3) NOT NULL,
  ts_client timestamp(3) DEFAULT NULL,
  app varchar(32) NOT NULL,
  env varchar(32) NOT NULL,
  release varchar(128) NOT NULL DEFAULT '',
  user_id varchar(64) DEFAULT NULL,
  username varchar(120) DEFAULT NULL,
  is_admin smallint NOT NULL DEFAULT 0,
  device_id varchar(128) NOT NULL,
  session_id varchar(128) NOT NULL,
  trace_id varchar(64) DEFAULT NULL,
  route varchar(256) NOT NULL DEFAULT '',
  user_agent varchar(512) NOT NULL DEFAULT '',
  name varchar(128) NOT NULL,
  payload jsonb DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_events_business_app_name_ts ON events_business (app, name, ts_server);
CREATE INDEX IF NOT EXISTS ix_events_business_ts ON events_business (ts_server);

-- ─── sessions ───────────────────────────────────────────────────
-- Composite PK lets ingestion use INSERT ... ON CONFLICT DO UPDATE so
-- multiple batches in the same session merge into one row (replaces the
-- ClickHouse ReplacingMergeTree(ts_server) semantics).
CREATE TABLE IF NOT EXISTS sessions (
  app varchar(32) NOT NULL,
  session_id varchar(128) NOT NULL,
  ts_server timestamp(3) NOT NULL,
  env varchar(32) NOT NULL,
  release varchar(128) NOT NULL DEFAULT '',
  user_id varchar(64) DEFAULT NULL,
  username varchar(120) DEFAULT NULL,
  is_admin smallint NOT NULL DEFAULT 0,
  device_id varchar(128) NOT NULL,
  route varchar(256) NOT NULL DEFAULT '',
  user_agent varchar(512) NOT NULL DEFAULT '',
  event_count integer NOT NULL DEFAULT 0,
  PRIMARY KEY (app, session_id)
);
CREATE INDEX IF NOT EXISTS ix_sessions_ts ON sessions (ts_server);

UPDATE migration SET version = 'v1.0.0', update_time = NOW() WHERE id = 1;
