apiVersion: v1
kind: ConfigMap
metadata:
  name: knowledge-config
data:
  ENVIRONMENT: "production"
  PORT: "8010"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "knowledge"
  ADMIN_SERVICE_URL: "http://admin:8001"
  EXECUTOR_SERVICE_URL: "http://executor:8011"
  ASSET_SERVICE_URL: "http://asset:8013"
  EMBEDDING_DIM: "2048"
