// Code generated by go generate; DO NOT EDIT.

package errno

import (
	"errors"
	"fmt"
)

type ErrorCode string

const (
	UnknownErrorCode ErrorCode = "Unknown"
)

const unknownBizCode int32 = 5000000

type ErrorMeta struct {
	Code     ErrorCode
	BizCode  int32
	HTTPCode int
	Message  string
	Comment  string
}

func (m ErrorMeta) IsZero() bool {
	return m.Code == ""
}

type BizError struct {
	Code    ErrorCode
	BizCode int32
	Message string
	Extra   map[string]string
	Cause   error
}

func (e *BizError) Error() string {
	if e == nil {
		return "<nil>"
	}
	if e.Cause != nil {
		return fmt.Sprintf("code=%s biz_code=%d message=%s cause=%v", e.Code, e.BizCode, e.Message, e.Cause)
	}
	return fmt.Sprintf("code=%s biz_code=%d message=%s", e.Code, e.BizCode, e.Message)
}

func (e *BizError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Cause
}

func (e *BizError) Is(target error) bool {
	if e == nil || target == nil {
		return false
	}
	other, ok := target.(*BizError)
	if !ok {
		return false
	}
	return e.Code != "" && e.Code == other.Code
}

func (e *BizError) WithMessage(message string) *BizError {
	if e == nil {
		return nil
	}
	clone := e.clone()
	clone.Message = message
	return clone
}

func (e *BizError) WithExtra(extra map[string]string) *BizError {
	if e == nil {
		return nil
	}
	clone := e.clone()
	clone.Extra = cloneStringMap(extra)
	return clone
}

func (e *BizError) WithCause(cause error) *BizError {
	if e == nil {
		return nil
	}
	clone := e.clone()
	clone.Cause = cause
	return clone
}

func (e *BizError) clone() *BizError {
	if e == nil {
		return nil
	}
	return &BizError{
		Code:    e.Code,
		BizCode: e.BizCode,
		Message: e.Message,
		Extra:   cloneStringMap(e.Extra),
		Cause:   e.Cause,
	}
}

func cloneStringMap(source map[string]string) map[string]string {
	if len(source) == 0 {
		return nil
	}
	cloned := make(map[string]string, len(source))
	for key, value := range source {
		cloned[key] = value
	}
	return cloned
}

const (
	// Invalid argument
	ErrInvalidArgument ErrorCode = "InvalidArgument"
	// The selected model does not exist, is not running, or lacks the required capability
	ErrModelUnavailable ErrorCode = "ModelUnavailable"
	// Project member list is empty
	ErrProjectMembersRequired ErrorCode = "ProjectMembersRequired"
	// Prompt references an asset that is no longer bound to the canvas node
	ErrCanvasNodeAssetMissing ErrorCode = "CanvasNodeAssetMissing"
	// Uploaded blob content is not a supported asset format
	ErrUnsupportedAssetFormat ErrorCode = "UnsupportedAssetFormat"
	// Uploaded asset exceeds the size limit for its media type
	ErrAssetTooLarge ErrorCode = "AssetTooLarge"
	// Project or Video cover image exceeds the 2 MiB limit
	ErrCoverImageTooLarge ErrorCode = "CoverImageTooLarge"
	// The selected asset media type is not supported by the resource type
	ErrResourceAssetMediaTypeMismatch ErrorCode = "ResourceAssetMediaTypeMismatch"
	// The selected asset is not owned by the requested resource
	ErrResourceAssetOwnerMismatch ErrorCode = "ResourceAssetOwnerMismatch"
	// The resource asset source type does not support the requested operation
	ErrResourceAssetSourceTypeMismatch ErrorCode = "ResourceAssetSourceTypeMismatch"
	// A generation reference is unavailable, unsupported, self-referential, or has no current image
	ErrResourceAssetGenerationReferenceInvalid ErrorCode = "ResourceAssetGenerationReferenceInvalid"
	// Access forbidden
	ErrForbidden ErrorCode = "Forbidden"
	// OFFICIAL resources and their assets are read-only and maintained by trusted reconciliation
	ErrResourceReadOnly ErrorCode = "ResourceReadOnly"
	// Resource not found
	ErrNotFound ErrorCode = "NotFound"
	// Resource does not exist or is outside the requested project scope
	ErrResourceNotFound ErrorCode = "ResourceNotFound"
	// Resource asset does not exist or is outside the requested resource scope
	ErrResourceAssetNotFound ErrorCode = "ResourceAssetNotFound"
	// The generated resource asset has no visible generation configuration or run
	ErrResourceAssetGenerationNotFound ErrorCode = "ResourceAssetGenerationNotFound"
	// Conflict
	ErrConflict ErrorCode = "Conflict"
	// Project name is already used in the tenant
	ErrProjectNameAlreadyExists ErrorCode = "ProjectNameAlreadyExists"
	// Canvas name is already used in the project
	ErrCanvasNameAlreadyExists ErrorCode = "CanvasNameAlreadyExists"
	// Project already contains the maximum number of active canvases
	ErrCanvasLimitExceeded ErrorCode = "CanvasLimitExceeded"
	// Canvas already contains the maximum number of active nodes
	ErrCanvasNodeLimitExceeded ErrorCode = "CanvasNodeLimitExceeded"
	// A task run already owns the canvas node
	ErrCanvasNodeGenerationInProgress ErrorCode = "CanvasNodeGenerationInProgress"
	// Canvas node already contains the maximum assets for the media type
	ErrCanvasNodeAssetLimitExceeded ErrorCode = "CanvasNodeAssetLimitExceeded"
	// An active canvas node with the same name already exists in the canvas
	ErrCanvasNodeNameConflict ErrorCode = "CanvasNodeNameConflict"
	// An active resource with the same name already exists in the project
	ErrResourceNameConflict ErrorCode = "ResourceNameConflict"
	// An active resource asset with the same name already exists in the resource
	ErrResourceAssetNameConflict ErrorCode = "ResourceAssetNameConflict"
	// The project resource type has reached its active resource limit
	ErrResourceLimitExceeded ErrorCode = "ResourceLimitExceeded"
	// The resource has reached its active resource asset limit
	ErrResourceAssetLimitExceeded ErrorCode = "ResourceAssetLimitExceeded"
	// The resource changed after the caller read it
	ErrResourceRevisionConflict ErrorCode = "ResourceRevisionConflict"
	// The resource asset changed after the caller read it
	ErrResourceAssetRevisionConflict ErrorCode = "ResourceAssetRevisionConflict"
	// The generation configuration changed after the caller read it
	ErrResourceAssetGenerationRevisionConflict ErrorCode = "ResourceAssetGenerationRevisionConflict"
	// The generated resource asset already has an active run
	ErrResourceAssetGenerationRunActive ErrorCode = "ResourceAssetGenerationRunActive"
	// The task run is not the active run for the generated resource asset
	ErrResourceAssetGenerationRunConflict ErrorCode = "ResourceAssetGenerationRunConflict"
	// Benefit package name is already used in the tenant
	ErrBenefitPackageNameAlreadyExists ErrorCode = "BenefitPackageNameAlreadyExists"
	// The tenant allocation has no remaining project capacity
	ErrProjectQuotaExceeded ErrorCode = "ProjectQuotaExceeded"
	// The tenant allocation has no remaining preset entitlement asset capacity
	ErrPresetEntitlementAssetQuotaExceeded ErrorCode = "PresetEntitlementAssetQuotaExceeded"
	// The tenant has no remaining storage capacity
	ErrStorageQuotaExceeded ErrorCode = "StorageQuotaExceeded"
	// Failed business precondition
	ErrFailedPrecondition ErrorCode = "FailedPrecondition"
	// The tenant has no default model configured for the requested capability
	ErrDefaultModelNotConfigured ErrorCode = "DefaultModelNotConfigured"
	// Prompt, model, resolution, or aspect ratio is incomplete
	ErrResourceAssetGenerationConfigIncomplete ErrorCode = "ResourceAssetGenerationConfigIncomplete"
	// Too many requests
	ErrTooManyRequests ErrorCode = "TooManyRequests"
	// Internal server error
	ErrInternalError ErrorCode = "InternalError"
	// Persistence dependency failure
	ErrPersistenceError ErrorCode = "PersistenceError"
	// External dependency failure
	ErrExternalDependencyError ErrorCode = "ExternalDependencyError"
	// Runtime configuration error
	ErrConfigurationError ErrorCode = "ConfigurationError"
	// Serialization failure
	ErrSerializationError ErrorCode = "SerializationError"
	// Redis dependency failure
	ErrRedisDependencyError ErrorCode = "RedisDependencyError"
	// Model dependency failure
	ErrModelDependencyError ErrorCode = "ModelDependencyError"
	// Object storage dependency failure
	ErrObjectStorageDependencyError ErrorCode = "ObjectStorageDependencyError"
	// Execution lane dependency failure
	ErrExecutionLaneDependencyError ErrorCode = "ExecutionLaneDependencyError"
	// Not implemented
	ErrNotImplemented ErrorCode = "NotImplemented"
	// Service unavailable
	ErrUnavailable ErrorCode = "Unavailable"
	// The quota store failed or a required quota row is unavailable
	ErrQuotaUnavailable ErrorCode = "QuotaUnavailable"
	// Request timeout
	ErrRequestTimeout ErrorCode = "RequestTimeout"
)

var allErrorMeta = []ErrorMeta{
	{
		Code:     ErrInvalidArgument,
		BizCode:  4000001,
		HTTPCode: 400,
		Message:  "invalid argument",
		Comment:  "Invalid argument",
	},
	{
		Code:     ErrModelUnavailable,
		BizCode:  4000002,
		HTTPCode: 400,
		Message:  "selected model is unavailable",
		Comment:  "The selected model does not exist, is not running, or lacks the required capability",
	},
	{
		Code:     ErrProjectMembersRequired,
		BizCode:  4001001,
		HTTPCode: 400,
		Message:  "project requires at least one member",
		Comment:  "Project member list is empty",
	},
	{
		Code:     ErrCanvasNodeAssetMissing,
		BizCode:  4002006,
		HTTPCode: 400,
		Message:  "canvas node asset is missing",
		Comment:  "Prompt references an asset that is no longer bound to the canvas node",
	},
	{
		Code:     ErrUnsupportedAssetFormat,
		BizCode:  4003001,
		HTTPCode: 400,
		Message:  "unsupported asset format",
		Comment:  "Uploaded blob content is not a supported asset format",
	},
	{
		Code:     ErrAssetTooLarge,
		BizCode:  4003003,
		HTTPCode: 400,
		Message:  "asset is too large",
		Comment:  "Uploaded asset exceeds the size limit for its media type",
	},
	{
		Code:     ErrCoverImageTooLarge,
		BizCode:  4004001,
		HTTPCode: 400,
		Message:  "cover image is too large",
		Comment:  "Project or Video cover image exceeds the 2 MiB limit",
	},
	{
		Code:     ErrResourceAssetMediaTypeMismatch,
		BizCode:  4005001,
		HTTPCode: 400,
		Message:  "resource asset media type mismatch",
		Comment:  "The selected asset media type is not supported by the resource type",
	},
	{
		Code:     ErrResourceAssetOwnerMismatch,
		BizCode:  4005002,
		HTTPCode: 400,
		Message:  "resource asset owner mismatch",
		Comment:  "The selected asset is not owned by the requested resource",
	},
	{
		Code:     ErrResourceAssetSourceTypeMismatch,
		BizCode:  4005003,
		HTTPCode: 400,
		Message:  "resource asset source type mismatch",
		Comment:  "The resource asset source type does not support the requested operation",
	},
	{
		Code:     ErrResourceAssetGenerationReferenceInvalid,
		BizCode:  4005004,
		HTTPCode: 400,
		Message:  "resource asset generation reference is invalid",
		Comment:  "A generation reference is unavailable, unsupported, self-referential, or has no current image",
	},
	{
		Code:     ErrForbidden,
		BizCode:  4030001,
		HTTPCode: 403,
		Message:  "forbidden",
		Comment:  "Access forbidden",
	},
	{
		Code:     ErrResourceReadOnly,
		BizCode:  4035001,
		HTTPCode: 403,
		Message:  "resource is read-only",
		Comment:  "OFFICIAL resources and their assets are read-only and maintained by trusted reconciliation",
	},
	{
		Code:     ErrNotFound,
		BizCode:  4040001,
		HTTPCode: 404,
		Message:  "not found",
		Comment:  "Resource not found",
	},
	{
		Code:     ErrResourceNotFound,
		BizCode:  4045001,
		HTTPCode: 404,
		Message:  "resource not found",
		Comment:  "Resource does not exist or is outside the requested project scope",
	},
	{
		Code:     ErrResourceAssetNotFound,
		BizCode:  4045002,
		HTTPCode: 404,
		Message:  "resource asset not found",
		Comment:  "Resource asset does not exist or is outside the requested resource scope",
	},
	{
		Code:     ErrResourceAssetGenerationNotFound,
		BizCode:  4045003,
		HTTPCode: 404,
		Message:  "resource asset generation not found",
		Comment:  "The generated resource asset has no visible generation configuration or run",
	},
	{
		Code:     ErrConflict,
		BizCode:  4090001,
		HTTPCode: 409,
		Message:  "conflict",
		Comment:  "Conflict",
	},
	{
		Code:     ErrProjectNameAlreadyExists,
		BizCode:  4091001,
		HTTPCode: 409,
		Message:  "project name already exists",
		Comment:  "Project name is already used in the tenant",
	},
	{
		Code:     ErrCanvasNameAlreadyExists,
		BizCode:  4092001,
		HTTPCode: 409,
		Message:  "canvas name already exists",
		Comment:  "Canvas name is already used in the project",
	},
	{
		Code:     ErrCanvasLimitExceeded,
		BizCode:  4092002,
		HTTPCode: 409,
		Message:  "canvas limit exceeded",
		Comment:  "Project already contains the maximum number of active canvases",
	},
	{
		Code:     ErrCanvasNodeLimitExceeded,
		BizCode:  4092003,
		HTTPCode: 409,
		Message:  "canvas node limit exceeded",
		Comment:  "Canvas already contains the maximum number of active nodes",
	},
	{
		Code:     ErrCanvasNodeGenerationInProgress,
		BizCode:  4092004,
		HTTPCode: 409,
		Message:  "canvas node generation is already in progress",
		Comment:  "A task run already owns the canvas node",
	},
	{
		Code:     ErrCanvasNodeAssetLimitExceeded,
		BizCode:  4092005,
		HTTPCode: 409,
		Message:  "canvas node asset limit exceeded",
		Comment:  "Canvas node already contains the maximum assets for the media type",
	},
	{
		Code:     ErrCanvasNodeNameConflict,
		BizCode:  4092007,
		HTTPCode: 409,
		Message:  "canvas node name already exists",
		Comment:  "An active canvas node with the same name already exists in the canvas",
	},
	{
		Code:     ErrResourceNameConflict,
		BizCode:  4095001,
		HTTPCode: 409,
		Message:  "resource name already exists",
		Comment:  "An active resource with the same name already exists in the project",
	},
	{
		Code:     ErrResourceAssetNameConflict,
		BizCode:  4095002,
		HTTPCode: 409,
		Message:  "resource asset name already exists",
		Comment:  "An active resource asset with the same name already exists in the resource",
	},
	{
		Code:     ErrResourceLimitExceeded,
		BizCode:  4095003,
		HTTPCode: 409,
		Message:  "resource limit exceeded",
		Comment:  "The project resource type has reached its active resource limit",
	},
	{
		Code:     ErrResourceAssetLimitExceeded,
		BizCode:  4095004,
		HTTPCode: 409,
		Message:  "resource asset limit exceeded",
		Comment:  "The resource has reached its active resource asset limit",
	},
	{
		Code:     ErrResourceRevisionConflict,
		BizCode:  4095005,
		HTTPCode: 409,
		Message:  "resource revision conflict",
		Comment:  "The resource changed after the caller read it",
	},
	{
		Code:     ErrResourceAssetRevisionConflict,
		BizCode:  4095006,
		HTTPCode: 409,
		Message:  "resource asset revision conflict",
		Comment:  "The resource asset changed after the caller read it",
	},
	{
		Code:     ErrResourceAssetGenerationRevisionConflict,
		BizCode:  4095007,
		HTTPCode: 409,
		Message:  "resource asset generation revision conflict",
		Comment:  "The generation configuration changed after the caller read it",
	},
	{
		Code:     ErrResourceAssetGenerationRunActive,
		BizCode:  4095008,
		HTTPCode: 409,
		Message:  "resource asset generation run is active",
		Comment:  "The generated resource asset already has an active run",
	},
	{
		Code:     ErrResourceAssetGenerationRunConflict,
		BizCode:  4095009,
		HTTPCode: 409,
		Message:  "resource asset generation run conflict",
		Comment:  "The task run is not the active run for the generated resource asset",
	},
	{
		Code:     ErrBenefitPackageNameAlreadyExists,
		BizCode:  4096001,
		HTTPCode: 409,
		Message:  "benefit package name already exists",
		Comment:  "Benefit package name is already used in the tenant",
	},
	{
		Code:     ErrProjectQuotaExceeded,
		BizCode:  4096002,
		HTTPCode: 409,
		Message:  "project quota exceeded",
		Comment:  "The tenant allocation has no remaining project capacity",
	},
	{
		Code:     ErrPresetEntitlementAssetQuotaExceeded,
		BizCode:  4096003,
		HTTPCode: 409,
		Message:  "preset entitlement asset quota exceeded",
		Comment:  "The tenant allocation has no remaining preset entitlement asset capacity",
	},
	{
		Code:     ErrStorageQuotaExceeded,
		BizCode:  4096004,
		HTTPCode: 409,
		Message:  "storage quota exceeded",
		Comment:  "The tenant has no remaining storage capacity",
	},
	{
		Code:     ErrFailedPrecondition,
		BizCode:  4120001,
		HTTPCode: 412,
		Message:  "failed precondition",
		Comment:  "Failed business precondition",
	},
	{
		Code:     ErrDefaultModelNotConfigured,
		BizCode:  4120002,
		HTTPCode: 412,
		Message:  "default model is not configured",
		Comment:  "The tenant has no default model configured for the requested capability",
	},
	{
		Code:     ErrResourceAssetGenerationConfigIncomplete,
		BizCode:  4125001,
		HTTPCode: 412,
		Message:  "resource asset generation config is incomplete",
		Comment:  "Prompt, model, resolution, or aspect ratio is incomplete",
	},
	{
		Code:     ErrTooManyRequests,
		BizCode:  4290001,
		HTTPCode: 429,
		Message:  "too many requests",
		Comment:  "Too many requests",
	},
	{
		Code:     ErrInternalError,
		BizCode:  5000000,
		HTTPCode: 500,
		Message:  "internal server error",
		Comment:  "Internal server error",
	},
	{
		Code:     ErrPersistenceError,
		BizCode:  5000001,
		HTTPCode: 500,
		Message:  "persistence error",
		Comment:  "Persistence dependency failure",
	},
	{
		Code:     ErrExternalDependencyError,
		BizCode:  5000002,
		HTTPCode: 500,
		Message:  "external dependency error",
		Comment:  "External dependency failure",
	},
	{
		Code:     ErrConfigurationError,
		BizCode:  5000004,
		HTTPCode: 500,
		Message:  "configuration error",
		Comment:  "Runtime configuration error",
	},
	{
		Code:     ErrSerializationError,
		BizCode:  5000005,
		HTTPCode: 500,
		Message:  "serialization error",
		Comment:  "Serialization failure",
	},
	{
		Code:     ErrRedisDependencyError,
		BizCode:  5000006,
		HTTPCode: 500,
		Message:  "redis dependency error",
		Comment:  "Redis dependency failure",
	},
	{
		Code:     ErrModelDependencyError,
		BizCode:  5000007,
		HTTPCode: 500,
		Message:  "model dependency error",
		Comment:  "Model dependency failure",
	},
	{
		Code:     ErrObjectStorageDependencyError,
		BizCode:  5000008,
		HTTPCode: 500,
		Message:  "object storage dependency error",
		Comment:  "Object storage dependency failure",
	},
	{
		Code:     ErrExecutionLaneDependencyError,
		BizCode:  5000010,
		HTTPCode: 500,
		Message:  "execution lane dependency error",
		Comment:  "Execution lane dependency failure",
	},
	{
		Code:     ErrNotImplemented,
		BizCode:  5010001,
		HTTPCode: 501,
		Message:  "not implemented",
		Comment:  "Not implemented",
	},
	{
		Code:     ErrUnavailable,
		BizCode:  5030001,
		HTTPCode: 503,
		Message:  "service unavailable",
		Comment:  "Service unavailable",
	},
	{
		Code:     ErrQuotaUnavailable,
		BizCode:  5036001,
		HTTPCode: 503,
		Message:  "resource quota is temporarily unavailable",
		Comment:  "The quota store failed or a required quota row is unavailable",
	},
	{
		Code:     ErrRequestTimeout,
		BizCode:  5040001,
		HTTPCode: 504,
		Message:  "request timed out",
		Comment:  "Request timeout",
	},
}

var (
	errorMetaIndex   map[ErrorCode]int
	bizCodeMetaIndex map[int32]int
)

func init() {
	errorMetaIndex = make(map[ErrorCode]int, len(allErrorMeta))
	bizCodeMetaIndex = make(map[int32]int, len(allErrorMeta))
	for index, meta := range allErrorMeta {
		errorMetaIndex[meta.Code] = index
		bizCodeMetaIndex[meta.BizCode] = index
	}
}

func Meta(code ErrorCode) ErrorMeta {
	if meta, ok := LookupMeta(code); ok {
		return meta
	}
	return UnknownMeta()
}

func UnknownMeta() ErrorMeta {
	return ErrorMeta{
		Code:     UnknownErrorCode,
		BizCode:  unknownBizCode,
		HTTPCode: 500,
		Message:  "unknown error",
		Comment:  "Unknown error",
	}
}

func MustMeta(code ErrorCode) ErrorMeta {
	meta, ok := LookupMeta(code)
	if !ok {
		panic(fmt.Sprintf("unknown error code: %s", code))
	}
	return meta
}

func LookupMeta(code ErrorCode) (ErrorMeta, bool) {
	index, ok := errorMetaIndex[code]
	if !ok {
		return ErrorMeta{}, false
	}
	return allErrorMeta[index], true
}

func CodeByBizCode(bizCode int32) (ErrorCode, bool) {
	index, ok := bizCodeMetaIndex[bizCode]
	if !ok {
		return "", false
	}
	return allErrorMeta[index].Code, true
}

func MetaByBizCode(bizCode int32) ErrorMeta {
	if code, ok := CodeByBizCode(bizCode); ok {
		return Meta(code)
	}
	return UnknownMeta()
}

func New(code ErrorCode) *BizError {
	meta := Meta(code)
	return &BizError{
		Code:    meta.Code,
		BizCode: meta.BizCode,
		Message: meta.Message,
	}
}

func NewWithMessage(code ErrorCode, message string) *BizError {
	return New(code).WithMessage(message)
}

func NewWithExtra(code ErrorCode, extra map[string]string) *BizError {
	return New(code).WithExtra(extra)
}

func Wrap(code ErrorCode, cause error) *BizError {
	return New(code).WithCause(cause)
}

func IsCode(err error, code ErrorCode) bool {
	return errors.Is(err, New(code))
}

func IsKnown(code ErrorCode) bool {
	_, ok := errorMetaIndex[code]
	return ok
}

func AllMeta() []ErrorMeta {
	items := make([]ErrorMeta, len(allErrorMeta))
	copy(items, allErrorMeta)
	return items
}
