apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monorepo-dev
resources:
  - ../../base/admin
  - ../../base/telemetry
  - ../../base/observability
images:
  - name: ghcr.io/example/admin
    newTag: dev
  - name: ghcr.io/example/telemetry
    newTag: dev
