apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monorepo-dev
resources:
  - ../../base/gateway
  - ../../base/iam
  - ../../base/admin
  - ../../base/telemetry
  - ../../base/ingress.yaml
images:
  - name: ghcr.io/example/gateway
    newTag: dev
  - name: ghcr.io/example/iam
    newTag: dev
  - name: ghcr.io/example/admin
    newTag: dev
  - name: ghcr.io/example/telemetry
    newTag: dev
