#!/usr/bin/env bash
# render-env.sh — assemble the compose `.env` ON THE VPS.
#
# The single-VPS stack pulls its env from three disjoint sources (see
# docs/ADR/0031). This script runs on the VPS every deploy and merges them
# into ${DEPLOY_DIR}/.env:
#
#   1. Runtime vars from the environment (set by deploy.sh / CI):
#        IMAGE_REGISTRY, IMAGE_TAG, PUBLIC_PORT
#   2. Machine-internal secrets — database passwords + INTERNAL_API_TOKEN —
#      auto-generated ONCE and persisted in ./.env.secrets. Humans never see
#      or type them. Regenerating is safe only on a fresh data volume, so we
#      generate-if-missing and otherwise reuse.
#   3. Operator secrets decrypted from the committed, SOPS-encrypted
#      ./secrets.sops.env (super-admin login, Exa/Tavily Search keys, and the
#      two must-stay-stable crypto secrets ACCESS_TOKEN_SECRET / ADMIN_SECRET_KEY).
#
# Idempotent. The persistence in (2) is REQUIRED for correctness, not just
# tidiness: the Postgres superuser password is fixed at first data-volume init
# and the ADMIN_SECRET_KEY Fernet key must never change once data exists.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SECRETS_FILE="${HERE}/.env.secrets"
SOPS_FILE="${HERE}/secrets.sops.env"
OUT="${HERE}/.env"
AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-${HERE}/age.key}"

# Internal secrets: 24 random bytes hex each. Order is irrelevant; compose reads
# them by name. Database passwords must stay stable after their first data
# volume init.
INTERNAL_KEYS=(
  WORKFLOW_POSTGRES_PASSWORD
  IAM_POSTGRES_PASSWORD
  ADMIN_POSTGRES_PASSWORD
  CHAT_POSTGRES_PASSWORD
  EXECUTOR_POSTGRES_PASSWORD
  KNOWLEDGE_POSTGRES_PASSWORD
  TELEMETRY_POSTGRES_PASSWORD
  CLICKHOUSE_PASSWORD
  INTERNAL_API_TOKEN
)

umask 077

# Fail closed: if the whole secrets file is gone but a Postgres data volume
# already exists, regenerating passwords would lock us out of the existing DB
# (the superuser password is fixed at first volume init and every service role
# already has its old password). Refuse and point at backup/restore. A file
# that merely LACKS a key (e.g. a newly added service) is fine — we add it.
if [ ! -s "${SECRETS_FILE}" ]; then
  PROJECT="${COMPOSE_PROJECT_NAME:-$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]')}"
  if docker volume inspect "${PROJECT}_postgres_data" >/dev/null 2>&1; then
    echo "✗ ${SECRETS_FILE} is missing but the Postgres data volume" >&2
    echo "  '${PROJECT}_postgres_data' already exists." >&2
    echo "  Regenerating passwords would lock you out of the existing database." >&2
    echo "  Restore ${SECRETS_FILE} from backup, OR wipe for a fresh start:" >&2
    echo "    docker compose -f docker-compose.prod.yml down -v" >&2
    exit 1
  fi
  echo "  (first init: generating internal secrets)"
fi

touch "${SECRETS_FILE}"
chmod 600 "${SECRETS_FILE}"
for key in "${INTERNAL_KEYS[@]}"; do
  if ! grep -qE "^${key}=" "${SECRETS_FILE}"; then
    printf '%s=%s\n' "${key}" "$(openssl rand -hex 24)" >> "${SECRETS_FILE}"
    echo "  + generated ${key}"
  fi
done

if [ ! -f "${SOPS_FILE}" ]; then
  echo "✗ ${SOPS_FILE} is missing." >&2
  echo "  Create it once from the template and commit it (it is encrypted):" >&2
  echo "    sops infra/single-vps/secrets.sops.env   # see .env.example alongside" >&2
  exit 1
fi
if [ ! -f "${AGE_KEY_FILE}" ]; then
  echo "✗ age key not found at ${AGE_KEY_FILE}." >&2
  echo "  Run infra/single-vps/bootstrap.sh on this VPS to generate it." >&2
  exit 1
fi

export SOPS_AGE_KEY_FILE="${AGE_KEY_FILE}"
operator_env="$(sops --decrypt --input-type dotenv --output-type dotenv "${SOPS_FILE}")"

# Enforce the classification boundary: operator secrets must not shadow the
# runtime/internal keys (a duplicate would override the generated/injected value
# since it is appended last), and must not still hold a CHANGE_ME placeholder.
RESERVED=(IMAGE_REGISTRY IMAGE_TAG PUBLIC_PORT "${INTERNAL_KEYS[@]}")
while IFS='=' read -r k v; do
  case "${k}" in ''|\#*) continue ;; esac
  for r in "${RESERVED[@]}"; do
    if [ "${k}" = "${r}" ]; then
      echo "✗ operator secret '${k}' collides with a reserved runtime/internal key." >&2
      echo "  Remove it from secrets.sops.env — those are generated/injected automatically." >&2
      exit 1
    fi
  done
  case "${v}" in
    CHANGE_ME|CHANGE_ME_*)
      echo "✗ operator secret '${k}' still has a CHANGE_ME placeholder." >&2
      echo "  Fill it in: sops infra/single-vps/secrets.sops.env" >&2
      exit 1 ;;
  esac
done <<EOF
${operator_env}
EOF

{
  echo "# Generated by render-env.sh — DO NOT EDIT."
  echo "# Sources: runtime env + .env.secrets (generated) + secrets.sops.env (sops)."
  echo "IMAGE_REGISTRY=${IMAGE_REGISTRY:?IMAGE_REGISTRY is required}"
  echo "IMAGE_TAG=${IMAGE_TAG:-main}"
  echo "PUBLIC_PORT=${PUBLIC_PORT:-8080}"
  cat "${SECRETS_FILE}"
  printf '%s\n' "${operator_env}"
} > "${OUT}"
chmod 600 "${OUT}"

echo "✓ wrote ${OUT}"
