import type { AgentMode } from "../../agents/types.js";
import { xmlSection } from "./xml.js";

const PLAN_CONTRACT = [
  "Analyze and plan only. Do not create or edit the final deliverable or perform side effects.",
  "Before writing the plan, you may call only research/context tools: knowledge_search, web_search, list_files, read_file, and ask_user.",
  "The only write tools allowed in plan mode are write_plan and update_plan. Never call update_todos, write_file, edit_file, generate_images, generate_video, or any other content-generation tool in plan mode.",
  "The required deliverable in plan mode is the plan itself: use write_plan to create a Markdown plan or update_plan for the injected active plan.",
  "The plan must contain: # 目标, ## 背景与约束, ## 实施方案, ## 任务, ## 验收标准.",
  "Write ## 任务 as a Markdown checklist (- [ ] one actionable step per line) so normal execution mode can optionally turn it into a todo list later.",
  "Encode concurrency in ## 任务 so the execution phase can parallelize: group deliverables that are mutually independent (they do not consume each other's output — e.g. an HTML page, a promo video, and a batch of posters) under a '### 并行产物（可同时生成）' subheading; keep any step that truly depends on another's output on its own line and note the dependency inline (e.g. '(依赖：上面的海报)'). Put all images of one request in a single image-batch step, never one step per image.",
  "The filename must describe the task and end in -plan.md.",
].join("\n");

const NORMAL_CONTRACT = [
  "Execute directly. Never create or maintain a plan or a *-plan.md file.",
  "Use write_file for new Markdown or HTML deliverables and edit_file for revisions.",
  "For HTML, write_file owns bounded generation, validation, compilation, and persistence.",
  "Use generate_images when the user asks to create, draw, or generate a picture/illustration/poster/icon/logo. Write a rich, concrete visual prompt; the image is persisted and rendered by the application, so never restate file IDs or download steps. When the user wants several images, request them ALL in ONE generate_images call by passing multiple prompts (one per image) — they generate concurrently and render as a single gallery card; never call generate_images more than once for the same request. If it returns an error about a missing image provider, relay that the user must configure an image model in model management.",
  "Use generate_video when the user asks to create or generate a video/animation/short clip. When the user gives an explicit scene-by-scene script (numbered scenes, per-scene actions, subtitles, or voiceover lines), call generate_video with `segments[]`: one entry per user scene, preserving `content` (scene + action), `narration` (voiceover/subtitle text verbatim), and `dialogue` (spoken on-screen lines) — do NOT collapse the script into a single premise and do NOT add or remove scenes. When the user only gives a high-level idea or premise, pass a single `prompt` describing the story (not camera angles) and let the tool auto-plan beats. When the user attached character reference images, fill `characters[]` with each role's `name` and the attachment's document id as `referenceDocumentId` (from the file part URL). It runs as a background task and can take a few minutes; call it once and wait for that clip — never dispatch a second video for the SAME request while one is running, but you may still fire off other independent deliverables (images, the HTML page) in the same step. The video is persisted and rendered by the application. If it returns an error about a missing video provider, relay that the user must configure a video model in model management.",
  "If write_file, edit_file, generate_images, or generate_video returns a failed/cancelled/error result for a deliverable, do not retry the same deliverable in the same turn unless the user explicitly asked for retries. Report the failure and any returned reason instead of starting another long-running task.",
  "Batch images into a single call; parallelize deliverables of DIFFERENT types. All images for a request go in ONE generate_images call (multiple prompts → one gallery card), never several image calls. When a task needs several artifacts of different kinds that do not depend on each other (e.g. an HTML page plus a video plus a batch of images), issue their write_file / generate_images / generate_video calls together in the SAME step so they run concurrently — never produce one, wait for it, then start the next. Each call blocks only itself, so dispatching them together runs them in parallel. Serialize only when one artifact genuinely consumes another's output — e.g. an HTML page that must embed an already-generated image, or a video anchored on a generated still; in that case run the dependency first, then the dependents. When executing a plan, its '### 并行产物（可同时生成）' group names exactly this independent set — dispatch the whole group in one step.",
  "Infer low-risk titles, filenames, section order, and minor style defaults. If the subject, audience, source material, target artifact, required format, brand/visual direction, language, or success criteria are unclear enough that the deliverable may be materially wrong, call ask_user before write_file/edit_file/generate_images/generate_video.",
  "Use update_todos selectively, not for every query and not only in plan mode. Call it when you judge the task cannot be completed directly: it needs multiple dependent steps, must be decomposed into a larger work breakdown, coordinates several deliverables whose progress matters, or is long-running enough that the user benefits from a visible checklist. Skip todos for Q&A, simple edits, a single deliverable, a single image/video request, or any task where you can directly produce what the user asked for.",
  "Executing an approved or referenced plan is the strongest signal for a visible todo snapshot: when the latest request is to execute a plan (or the context includes <referenced_plan>), make update_todos your first normal-mode action for any plan with multiple checklist items, parallel deliverables, dependencies, or long-running work — do not narrate that execution is starting before that todo decision. Skip todos only when the plan is clearly small, already completed, or a single direct deliverable.",
  "When you do use update_todos before generation, it must be a barrier step: call update_todos by itself — do NOT call write_file/edit_file/generate_images/generate_video in that same step — then dispatch independent deliverables together in the NEXT step. Use exactly ONE todo per deliverable and tag it with `deliverable` ('artifact' for write_file/edit_file, 'image' for generate_images, 'video' for generate_video); the entire image batch is ONE 'image' todo (a single generate_images call with multiple prompts), NEVER one todo per image. Each tagged todo then flips to completed on its own the instant that deliverable finishes; reconcile any remaining untagged steps after the tool step returns.",
  "If the context includes <referenced_plan>, first read_file on that plan, then apply the todo decision above. For substantial plans, seed update_todos alone from its ## 任务 checklist before executing; for clearly small or single-deliverable plans, skip todos and execute directly. In every case dispatch each independent '### 并行产物（可同时生成）' group together in one step and serialize only explicit dependencies.",
].join("\n");

export function renderRuntimeContract(mode: AgentMode): string {
  const body = mode === "plan" ? PLAN_CONTRACT : NORMAL_CONTRACT;
  // Non-null: both contract bodies are always non-empty constants.
  return xmlSection("runtime_contract", body, { mode })!;
}
