apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clickhouse-statefulset.yaml
  - clickhouse-service.yaml
configMapGenerator:
  - name: clickhouse-init-sql
    files:
      - ../../../observability/clickhouse/init.sql
  - name: clickhouse-dev-user
    files:
      - ../../../observability/clickhouse/dev-user.xml
