apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
data:
  PORT: "8001"
  ENVIRONMENT: "development"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "admin"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
