apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
data:
  PORT: "8010"
  ENVIRONMENT: "development"
  MYSQL_PORT: "3306"
  STORAGE_MYSQL_DATABASE: "storage"
  STORAGE_DATA_DIR: "/data/storage"
  STORAGE_MAX_OBJECT_BYTES: "10485760"

